# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eyeParserBuilder.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 773)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsL.sizePolicy().hasHeightForWidth())
        self.settingsL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.settingsL.setFont(font)
        self.settingsL.setObjectName("settingsL")
        self.verticalLayout.addWidget(self.settingsL)
        self.settingsLine = QtWidgets.QFrame(self.centralwidget)
        self.settingsLine.setBaseSize(QtCore.QSize(0, 0))
        self.settingsLine.setLineWidth(5)
        self.settingsLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.settingsLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.settingsLine.setObjectName("settingsLine")
        self.verticalLayout.addWidget(self.settingsLine)
        self.regL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regL.sizePolicy().hasHeightForWidth())
        self.regL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.regL.setFont(font)
        self.regL.setObjectName("regL")
        self.verticalLayout.addWidget(self.regL)
        self.regSampL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regSampL.sizePolicy().hasHeightForWidth())
        self.regSampL.setSizePolicy(sizePolicy)
        self.regSampL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regSampL.setObjectName("regSampL")
        self.verticalLayout.addWidget(self.regSampL)
        self.regSamp = QtWidgets.QTextEdit(self.centralwidget)
        self.regSamp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regSamp.sizePolicy().hasHeightForWidth())
        self.regSamp.setSizePolicy(sizePolicy)
        self.regSamp.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regSamp.setObjectName("regSamp")
        self.verticalLayout.addWidget(self.regSamp)
        self.regEfixL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEfixL.sizePolicy().hasHeightForWidth())
        self.regEfixL.setSizePolicy(sizePolicy)
        self.regEfixL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEfixL.setObjectName("regEfixL")
        self.verticalLayout.addWidget(self.regEfixL)
        self.regEfix = QtWidgets.QTextEdit(self.centralwidget)
        self.regEfix.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEfix.sizePolicy().hasHeightForWidth())
        self.regEfix.setSizePolicy(sizePolicy)
        self.regEfix.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEfix.setObjectName("regEfix")
        self.verticalLayout.addWidget(self.regEfix)
        self.regEsaccL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEsaccL.sizePolicy().hasHeightForWidth())
        self.regEsaccL.setSizePolicy(sizePolicy)
        self.regEsaccL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEsaccL.setObjectName("regEsaccL")
        self.verticalLayout.addWidget(self.regEsaccL)
        self.regEsacc = QtWidgets.QTextEdit(self.centralwidget)
        self.regEsacc.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEsacc.sizePolicy().hasHeightForWidth())
        self.regEsacc.setSizePolicy(sizePolicy)
        self.regEsacc.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEsacc.setObjectName("regEsacc")
        self.verticalLayout.addWidget(self.regEsacc)
        self.regEblinkL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEblinkL.sizePolicy().hasHeightForWidth())
        self.regEblinkL.setSizePolicy(sizePolicy)
        self.regEblinkL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEblinkL.setObjectName("regEblinkL")
        self.verticalLayout.addWidget(self.regEblinkL)
        self.regEblink = QtWidgets.QTextEdit(self.centralwidget)
        self.regEblink.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEblink.sizePolicy().hasHeightForWidth())
        self.regEblink.setSizePolicy(sizePolicy)
        self.regEblink.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEblink.setObjectName("regEblink")
        self.verticalLayout.addWidget(self.regEblink)
        self.regStartL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStartL.sizePolicy().hasHeightForWidth())
        self.regStartL.setSizePolicy(sizePolicy)
        self.regStartL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStartL.setObjectName("regStartL")
        self.verticalLayout.addWidget(self.regStartL)
        self.regStart = QtWidgets.QTextEdit(self.centralwidget)
        self.regStart.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStart.sizePolicy().hasHeightForWidth())
        self.regStart.setSizePolicy(sizePolicy)
        self.regStart.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStart.setBaseSize(QtCore.QSize(0, 0))
        self.regStart.setObjectName("regStart")
        self.verticalLayout.addWidget(self.regStart)
        self.regStopL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStopL.sizePolicy().hasHeightForWidth())
        self.regStopL.setSizePolicy(sizePolicy)
        self.regStopL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStopL.setObjectName("regStopL")
        self.verticalLayout.addWidget(self.regStopL)
        self.regStop = QtWidgets.QTextEdit(self.centralwidget)
        self.regStop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStop.sizePolicy().hasHeightForWidth())
        self.regStop.setSizePolicy(sizePolicy)
        self.regStop.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStop.setObjectName("regStop")
        self.verticalLayout.addWidget(self.regStop)
        self.regVarL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regVarL.sizePolicy().hasHeightForWidth())
        self.regVarL.setSizePolicy(sizePolicy)
        self.regVarL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regVarL.setObjectName("regVarL")
        self.verticalLayout.addWidget(self.regVarL)
        self.regVar = QtWidgets.QTextEdit(self.centralwidget)
        self.regVar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regVar.sizePolicy().hasHeightForWidth())
        self.regVar.setSizePolicy(sizePolicy)
        self.regVar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regVar.setObjectName("regVar")
        self.verticalLayout.addWidget(self.regVar)
        self.regMsgL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regMsgL.sizePolicy().hasHeightForWidth())
        self.regMsgL.setSizePolicy(sizePolicy)
        self.regMsgL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regMsgL.setObjectName("regMsgL")
        self.verticalLayout.addWidget(self.regMsgL)
        self.regMsg = QtWidgets.QTextEdit(self.centralwidget)
        self.regMsg.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regMsg.sizePolicy().hasHeightForWidth())
        self.regMsg.setSizePolicy(sizePolicy)
        self.regMsg.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regMsg.setObjectName("regMsg")
        self.verticalLayout.addWidget(self.regMsg)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mergeL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeL.sizePolicy().hasHeightForWidth())
        self.mergeL.setSizePolicy(sizePolicy)
        self.mergeL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mergeL.setObjectName("mergeL")
        self.gridLayout_3.addWidget(self.mergeL, 1, 3, 1, 1)
        self.mergebtn = QtWidgets.QComboBox(self.centralwidget)
        self.mergebtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergebtn.sizePolicy().hasHeightForWidth())
        self.mergebtn.setSizePolicy(sizePolicy)
        self.mergebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.mergebtn.setObjectName("mergebtn")
        self.gridLayout_3.addWidget(self.mergebtn, 2, 3, 1, 1)
        self.duplicLongL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duplicLongL.sizePolicy().hasHeightForWidth())
        self.duplicLongL.setSizePolicy(sizePolicy)
        self.duplicLongL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.duplicLongL.setObjectName("duplicLongL")
        self.gridLayout_3.addWidget(self.duplicLongL, 4, 4, 1, 1)
        self.mergedName = QtWidgets.QTextEdit(self.centralwidget)
        self.mergedName.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergedName.sizePolicy().hasHeightForWidth())
        self.mergedName.setSizePolicy(sizePolicy)
        self.mergedName.setMaximumSize(QtCore.QSize(100, 25))
        self.mergedName.setObjectName("mergedName")
        self.gridLayout_3.addWidget(self.mergedName, 2, 2, 1, 1)
        self.rawNameL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawNameL.sizePolicy().hasHeightForWidth())
        self.rawNameL.setSizePolicy(sizePolicy)
        self.rawNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rawNameL.setObjectName("rawNameL")
        self.gridLayout_3.addWidget(self.rawNameL, 1, 1, 1, 1)
        self.parsedName = QtWidgets.QTextEdit(self.centralwidget)
        self.parsedName.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parsedName.sizePolicy().hasHeightForWidth())
        self.parsedName.setSizePolicy(sizePolicy)
        self.parsedName.setMaximumSize(QtCore.QSize(100, 25))
        self.parsedName.setObjectName("parsedName")
        self.gridLayout_3.addWidget(self.parsedName, 2, 0, 1, 1)
        self.longL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longL.sizePolicy().hasHeightForWidth())
        self.longL.setSizePolicy(sizePolicy)
        self.longL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.longL.setObjectName("longL")
        self.gridLayout_3.addWidget(self.longL, 4, 3, 1, 1)
        self.parsedNameL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parsedNameL.sizePolicy().hasHeightForWidth())
        self.parsedNameL.setSizePolicy(sizePolicy)
        self.parsedNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.parsedNameL.setObjectName("parsedNameL")
        self.gridLayout_3.addWidget(self.parsedNameL, 1, 0, 1, 1)
        self.saveRawL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawL.sizePolicy().hasHeightForWidth())
        self.saveRawL.setSizePolicy(sizePolicy)
        self.saveRawL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.saveRawL.setObjectName("saveRawL")
        self.gridLayout_3.addWidget(self.saveRawL, 1, 4, 1, 1)
        self.pixDegL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixDegL.sizePolicy().hasHeightForWidth())
        self.pixDegL.setSizePolicy(sizePolicy)
        self.pixDegL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pixDegL.setObjectName("pixDegL")
        self.gridLayout_3.addWidget(self.pixDegL, 4, 1, 1, 1)
        self.variousL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variousL.sizePolicy().hasHeightForWidth())
        self.variousL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.variousL.setFont(font)
        self.variousL.setObjectName("variousL")
        self.gridLayout_3.addWidget(self.variousL, 0, 0, 1, 1)
        self.rawName = QtWidgets.QTextEdit(self.centralwidget)
        self.rawName.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawName.sizePolicy().hasHeightForWidth())
        self.rawName.setSizePolicy(sizePolicy)
        self.rawName.setMaximumSize(QtCore.QSize(100, 25))
        self.rawName.setObjectName("rawName")
        self.gridLayout_3.addWidget(self.rawName, 2, 1, 1, 1)
        self.mergedNameL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergedNameL.sizePolicy().hasHeightForWidth())
        self.mergedNameL.setSizePolicy(sizePolicy)
        self.mergedNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mergedNameL.setObjectName("mergedNameL")
        self.gridLayout_3.addWidget(self.mergedNameL, 1, 2, 1, 1)
        self.pixPerDeg = QtWidgets.QTextEdit(self.centralwidget)
        self.pixPerDeg.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixPerDeg.sizePolicy().hasHeightForWidth())
        self.pixPerDeg.setSizePolicy(sizePolicy)
        self.pixPerDeg.setMaximumSize(QtCore.QSize(100, 25))
        self.pixPerDeg.setObjectName("pixPerDeg")
        self.gridLayout_3.addWidget(self.pixPerDeg, 7, 1, 1, 1)
        self.longbtn = QtWidgets.QComboBox(self.centralwidget)
        self.longbtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longbtn.sizePolicy().hasHeightForWidth())
        self.longbtn.setSizePolicy(sizePolicy)
        self.longbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.longbtn.setObjectName("longbtn")
        self.gridLayout_3.addWidget(self.longbtn, 5, 3, 1, 1)
        self.nrCoresL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nrCoresL.sizePolicy().hasHeightForWidth())
        self.nrCoresL.setSizePolicy(sizePolicy)
        self.nrCoresL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.nrCoresL.setObjectName("nrCoresL")
        self.gridLayout_3.addWidget(self.nrCoresL, 6, 0, 1, 1)
        self.pixPerDegL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixPerDegL.sizePolicy().hasHeightForWidth())
        self.pixPerDegL.setSizePolicy(sizePolicy)
        self.pixPerDegL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pixPerDegL.setObjectName("pixPerDegL")
        self.gridLayout_3.addWidget(self.pixPerDegL, 6, 1, 1, 1)
        self.nrCores = QtWidgets.QTextEdit(self.centralwidget)
        self.nrCores.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nrCores.sizePolicy().hasHeightForWidth())
        self.nrCores.setSizePolicy(sizePolicy)
        self.nrCores.setMaximumSize(QtCore.QSize(100, 25))
        self.nrCores.setObjectName("nrCores")
        self.gridLayout_3.addWidget(self.nrCores, 7, 0, 1, 1)
        self.paralell = QtWidgets.QComboBox(self.centralwidget)
        self.paralell.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paralell.sizePolicy().hasHeightForWidth())
        self.paralell.setSizePolicy(sizePolicy)
        self.paralell.setMaximumSize(QtCore.QSize(100, 25))
        self.paralell.setObjectName("paralell")
        self.gridLayout_3.addWidget(self.paralell, 5, 0, 1, 1)
        self.saveRawbtn = QtWidgets.QComboBox(self.centralwidget)
        self.saveRawbtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawbtn.sizePolicy().hasHeightForWidth())
        self.saveRawbtn.setSizePolicy(sizePolicy)
        self.saveRawbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.saveRawbtn.setObjectName("saveRawbtn")
        self.gridLayout_3.addWidget(self.saveRawbtn, 2, 4, 1, 1)
        self.pixMode = QtWidgets.QComboBox(self.centralwidget)
        self.pixMode.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixMode.sizePolicy().hasHeightForWidth())
        self.pixMode.setSizePolicy(sizePolicy)
        self.pixMode.setMaximumSize(QtCore.QSize(100, 25))
        self.pixMode.setObjectName("pixMode")
        self.gridLayout_3.addWidget(self.pixMode, 5, 1, 1, 1)
        self.paralellL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paralellL.sizePolicy().hasHeightForWidth())
        self.paralellL.setSizePolicy(sizePolicy)
        self.paralellL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.paralellL.setObjectName("paralellL")
        self.gridLayout_3.addWidget(self.paralellL, 4, 0, 1, 1)
        self.duplicLongbtn = QtWidgets.QComboBox(self.centralwidget)
        self.duplicLongbtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duplicLongbtn.sizePolicy().hasHeightForWidth())
        self.duplicLongbtn.setSizePolicy(sizePolicy)
        self.duplicLongbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.duplicLongbtn.setObjectName("duplicLongbtn")
        self.gridLayout_3.addWidget(self.duplicLongbtn, 5, 4, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textbox = QtWidgets.QTextEdit(self.centralwidget)
        self.textbox.setEnabled(False)
        self.textbox.setObjectName("textbox")
        self.gridLayout_2.addWidget(self.textbox, 1, 0, 1, 1)
        self.filebtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filebtn.sizePolicy().hasHeightForWidth())
        self.filebtn.setSizePolicy(sizePolicy)
        self.filebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.filebtn.setObjectName("filebtn")
        self.gridLayout_2.addWidget(self.filebtn, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 2, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.varKeyL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varKeyL.sizePolicy().hasHeightForWidth())
        self.varKeyL.setSizePolicy(sizePolicy)
        self.varKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.varKeyL.setObjectName("varKeyL")
        self.gridLayout.addWidget(self.varKeyL, 0, 2, 1, 1)
        self.startKey = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startKey.sizePolicy().hasHeightForWidth())
        self.startKey.setSizePolicy(sizePolicy)
        self.startKey.setMaximumSize(QtCore.QSize(100, 25))
        self.startKey.setObjectName("startKey")
        self.gridLayout.addWidget(self.startKey, 1, 0, 1, 1)
        self.Parsebtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Parsebtn.sizePolicy().hasHeightForWidth())
        self.Parsebtn.setSizePolicy(sizePolicy)
        self.Parsebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.Parsebtn.setObjectName("Parsebtn")
        self.gridLayout.addWidget(self.Parsebtn, 1, 3, 1, 1)
        self.varKey = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varKey.sizePolicy().hasHeightForWidth())
        self.varKey.setSizePolicy(sizePolicy)
        self.varKey.setMaximumSize(QtCore.QSize(100, 25))
        self.varKey.setObjectName("varKey")
        self.gridLayout.addWidget(self.varKey, 1, 2, 1, 1)
        self.startKeyL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startKeyL.sizePolicy().hasHeightForWidth())
        self.startKeyL.setSizePolicy(sizePolicy)
        self.startKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.startKeyL.setObjectName("startKeyL")
        self.gridLayout.addWidget(self.startKeyL, 0, 0, 1, 1)
        self.stopKeyL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopKeyL.sizePolicy().hasHeightForWidth())
        self.stopKeyL.setSizePolicy(sizePolicy)
        self.stopKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.stopKeyL.setObjectName("stopKeyL")
        self.gridLayout.addWidget(self.stopKeyL, 0, 1, 1, 1)
        self.stopKey = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopKey.sizePolicy().hasHeightForWidth())
        self.stopKey.setSizePolicy(sizePolicy)
        self.stopKey.setMaximumSize(QtCore.QSize(100, 25))
        self.stopKey.setObjectName("stopKey")
        self.gridLayout.addWidget(self.stopKey, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statusL = QtWidgets.QLabel(self.centralwidget)
        self.statusL.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusL.setFont(font)
        self.statusL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusL.setAlignment(QtCore.Qt.AlignCenter)
        self.statusL.setObjectName("statusL")
        self.verticalLayout_2.addWidget(self.statusL)
        self.bussyBar = QtWidgets.QProgressBar(self.centralwidget)
        self.bussyBar.setMaximum(1)
        self.bussyBar.setProperty("value", -1)
        self.bussyBar.setObjectName("bussyBar")
        self.verticalLayout_2.addWidget(self.bussyBar)
        self.progressBarL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarL.sizePolicy().hasHeightForWidth())
        self.progressBarL.setSizePolicy(sizePolicy)
        self.progressBarL.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBarL.setFont(font)
        self.progressBarL.setScaledContents(False)
        self.progressBarL.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBarL.setObjectName("progressBarL")
        self.verticalLayout_2.addWidget(self.progressBarL)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.cpuBarL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuBarL.sizePolicy().hasHeightForWidth())
        self.cpuBarL.setSizePolicy(sizePolicy)
        self.cpuBarL.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cpuBarL.setFont(font)
        self.cpuBarL.setObjectName("cpuBarL")
        self.verticalLayout_2.addWidget(self.cpuBarL)
        self.cpuBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuBar.sizePolicy().hasHeightForWidth())
        self.cpuBar.setSizePolicy(sizePolicy)
        self.cpuBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.cpuBar.setProperty("value", 24)
        self.cpuBar.setObjectName("cpuBar")
        self.verticalLayout_2.addWidget(self.cpuBar)
        self.memBarL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memBarL.sizePolicy().hasHeightForWidth())
        self.memBarL.setSizePolicy(sizePolicy)
        self.memBarL.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.memBarL.setFont(font)
        self.memBarL.setObjectName("memBarL")
        self.verticalLayout_2.addWidget(self.memBarL)
        self.memBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memBar.sizePolicy().hasHeightForWidth())
        self.memBar.setSizePolicy(sizePolicy)
        self.memBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.memBar.setProperty("value", 24)
        self.memBar.setObjectName("memBar")
        self.verticalLayout_2.addWidget(self.memBar)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setObjectName("openFile")
        self.quitParser = QtWidgets.QAction(MainWindow)
        self.quitParser.setShortcut("")
        self.quitParser.setObjectName("quitParser")
        self.unlockSettingsM = QtWidgets.QAction(MainWindow)
        self.unlockSettingsM.setObjectName("unlockSettingsM")
        self.lockSettingsM = QtWidgets.QAction(MainWindow)
        self.lockSettingsM.setEnabled(False)
        self.lockSettingsM.setObjectName("lockSettingsM")
        self.defSett = QtWidgets.QAction(MainWindow)
        self.defSett.setObjectName("defSett")
        self.openDoc = QtWidgets.QAction(MainWindow)
        self.openDoc.setObjectName("openDoc")
        self.menuFile.addAction(self.openFile)
        self.menuFile.addAction(self.quitParser)
        self.menuSettings.addAction(self.unlockSettingsM)
        self.menuSettings.addAction(self.lockSettingsM)
        self.menuSettings.addAction(self.defSett)
        self.menuSettings.addAction(self.openDoc)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eyelink 100 parser"))
        self.settingsL.setText(_translate("MainWindow", "Settings"))
        self.regL.setText(_translate("MainWindow", "Regular expressions for data extraction"))
        self.regSampL.setText(_translate("MainWindow", "Samples"))
        self.regEfixL.setText(_translate("MainWindow", "End fixation"))
        self.regEsaccL.setText(_translate("MainWindow", "End Saccade"))
        self.regEblinkL.setText(_translate("MainWindow", "End blink"))
        self.regStartL.setText(_translate("MainWindow", "Start trial"))
        self.regStopL.setText(_translate("MainWindow", "Stop trial"))
        self.regVarL.setText(_translate("MainWindow", "Variables"))
        self.regMsgL.setText(_translate("MainWindow", "Other messages"))
        self.mergeL.setText(_translate("MainWindow", "Merge files"))
        self.duplicLongL.setText(_translate("MainWindow", "Duplicate values"))
        self.rawNameL.setText(_translate("MainWindow", "Raw name"))
        self.longL.setText(_translate("MainWindow", "Save longformat"))
        self.parsedNameL.setText(_translate("MainWindow", "Parsed name"))
        self.saveRawL.setText(_translate("MainWindow", "Save raw file"))
        self.pixDegL.setText(_translate("MainWindow", "Pixels per degree"))
        self.variousL.setText(_translate("MainWindow", "Various settings"))
        self.mergedNameL.setText(_translate("MainWindow", "Merged name"))
        self.nrCoresL.setText(_translate("MainWindow", "CPU cores"))
        self.pixPerDegL.setText(_translate("MainWindow", "Px per deg (manual)"))
        self.paralellL.setText(_translate("MainWindow", "Parallel processing"))
        self.filebtn.setText(_translate("MainWindow", "Select file(s)"))
        self.varKeyL.setText(_translate("MainWindow", "Variable prefix"))
        self.Parsebtn.setText(_translate("MainWindow", "Parse"))
        self.startKeyL.setText(_translate("MainWindow", "Start trial key"))
        self.stopKeyL.setText(_translate("MainWindow", "Stop trial key"))
        self.statusL.setText(_translate("MainWindow", "Parallel processing!"))
        self.progressBarL.setText(_translate("MainWindow", "% of files Finished"))
        self.cpuBarL.setText(_translate("MainWindow", "CPU usage"))
        self.memBarL.setText(_translate("MainWindow", "Memory usage"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.openFile.setText(_translate("MainWindow", "Select files(s)"))
        self.openFile.setStatusTip(_translate("MainWindow", "Select file(s)"))
        self.quitParser.setText(_translate("MainWindow", "Exit"))
        self.quitParser.setStatusTip(_translate("MainWindow", "Exit parser"))
        self.unlockSettingsM.setText(_translate("MainWindow", "Unlock settings"))
        self.unlockSettingsM.setStatusTip(_translate("MainWindow", "Unlock settings"))
        self.lockSettingsM.setText(_translate("MainWindow", "Lock settings"))
        self.lockSettingsM.setStatusTip(_translate("MainWindow", "Lock settings"))
        self.defSett.setText(_translate("MainWindow", "Load default settings"))
        self.defSett.setStatusTip(_translate("MainWindow", "Load default setings"))
        self.openDoc.setText(_translate("MainWindow", "Documentation"))
        self.openDoc.setStatusTip(_translate("MainWindow", "Open documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

