# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotterGUICode.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Eyelinkplotter(object):
    def setupUi(self, Eyelinkplotter):
        Eyelinkplotter.setObjectName("Eyelinkplotter")
        Eyelinkplotter.setEnabled(True)
        Eyelinkplotter.resize(798, 635)
        self.centralwidget = QtWidgets.QWidget(Eyelinkplotter)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(240, 80, 496, 124))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.jumpToTrialNr = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.jumpToTrialNr.setMinimum(1)
        self.jumpToTrialNr.setMaximum(1000000)
        self.jumpToTrialNr.setObjectName("jumpToTrialNr")
        self.gridLayout.addWidget(self.jumpToTrialNr, 2, 4, 1, 1)
        self.backButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.backButton.setEnabled(True)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 4, 1, 1, 1)
        self.nextButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.nextButton.setEnabled(True)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 4, 3, 1, 1)
        self.updateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.updateButton.setEnabled(True)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout.addWidget(self.updateButton, 4, 2, 1, 1)
        self.jumpToTrial = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.jumpToTrial.setObjectName("jumpToTrial")
        self.gridLayout.addWidget(self.jumpToTrial, 4, 4, 1, 1)
        self.trialsToPlot = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.trialsToPlot.setObjectName("trialsToPlot")
        self.trialsToPlot.addItem("")
        self.trialsToPlot.addItem("")
        self.trialsToPlot.addItem("")
        self.gridLayout.addWidget(self.trialsToPlot, 4, 0, 1, 1)
        self.trialScroll = QtWidgets.QScrollBar(self.gridLayoutWidget)
        self.trialScroll.setMaximum(0)
        self.trialScroll.setOrientation(QtCore.Qt.Horizontal)
        self.trialScroll.setObjectName("trialScroll")
        self.gridLayout.addWidget(self.trialScroll, 5, 0, 1, 5)
        self.includedOrExcluded = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.includedOrExcluded.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.includedOrExcluded.setFont(font)
        self.includedOrExcluded.setObjectName("includedOrExcluded")
        self.gridLayout.addWidget(self.includedOrExcluded, 2, 0, 1, 1)
        self.currentTrialDisp = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currentTrialDisp.setFont(font)
        self.currentTrialDisp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.currentTrialDisp.setObjectName("currentTrialDisp")
        self.gridLayout.addWidget(self.currentTrialDisp, 2, 2, 1, 1)
        self.toggleIncluded = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.toggleIncluded.setObjectName("toggleIncluded")
        self.gridLayout.addWidget(self.toggleIncluded, 2, 1, 1, 1)
        self.animateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.animateButton.setObjectName("animateButton")
        self.gridLayout.addWidget(self.animateButton, 4, 5, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 160, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectFile = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.selectFile.setAutoDefault(False)
        self.selectFile.setDefault(False)
        self.selectFile.setFlat(False)
        self.selectFile.setObjectName("selectFile")
        self.gridLayout_2.addWidget(self.selectFile, 0, 0, 1, 1)
        self.selectedFile = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.selectedFile.setEnabled(False)
        self.selectedFile.setObjectName("selectedFile")
        self.gridLayout_2.addWidget(self.selectedFile, 2, 0, 1, 1)
        self.unLockSettings = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.unLockSettings.setObjectName("unLockSettings")
        self.gridLayout_2.addWidget(self.unLockSettings, 4, 0, 1, 1)
        self.saveFile = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.saveFile.setEnabled(False)
        self.saveFile.setObjectName("saveFile")
        self.gridLayout_2.addWidget(self.saveFile, 3, 0, 1, 1)
        self.heatmapTab = QtWidgets.QTabWidget(self.centralwidget)
        self.heatmapTab.setEnabled(False)
        self.heatmapTab.setGeometry(QtCore.QRect(10, 210, 771, 381))
        self.heatmapTab.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.heatmapTab.setObjectName("heatmapTab")
        self.windowTab = QtWidgets.QWidget()
        self.windowTab.setObjectName("windowTab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.windowTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 261, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plotType = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.plotType.setObjectName("plotType")
        self.gridLayout_3.addWidget(self.plotType, 1, 0, 1, 1)
        self.aspectRatio = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.aspectRatio.setObjectName("aspectRatio")
        self.gridLayout_3.addWidget(self.aspectRatio, 1, 1, 1, 1)
        self.plotTypeLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.plotTypeLabel.setObjectName("plotTypeLabel")
        self.gridLayout_3.addWidget(self.plotTypeLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.aspectRatioLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.aspectRatioLabel.setObjectName("aspectRatioLabel")
        self.gridLayout_3.addWidget(self.aspectRatioLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.windowTab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 220, 591, 81))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plotBackground = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.plotBackground.setObjectName("plotBackground")
        self.plotBackground.addItem("")
        self.plotBackground.addItem("")
        self.gridLayout_5.addWidget(self.plotBackground, 1, 0, 1, 1)
        self.backgroundMainLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.backgroundMainLabel.setFont(font)
        self.backgroundMainLabel.setObjectName("backgroundMainLabel")
        self.gridLayout_5.addWidget(self.backgroundMainLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.bgImageVariable = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.bgImageVariable.setObjectName("bgImageVariable")
        self.gridLayout_5.addWidget(self.bgImageVariable, 1, 2, 1, 1)
        self.selectImageFolder = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.selectImageFolder.setObjectName("selectImageFolder")
        self.gridLayout_5.addWidget(self.selectImageFolder, 1, 1, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.windowTab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 120, 591, 71))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.xMaxLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.xMaxLabel.setObjectName("xMaxLabel")
        self.gridLayout_6.addWidget(self.xMaxLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.xMaxValue = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.xMaxValue.setMinimum(-10000)
        self.xMaxValue.setMaximum(10000)
        self.xMaxValue.setObjectName("xMaxValue")
        self.gridLayout_6.addWidget(self.xMaxValue, 1, 1, 1, 1)
        self.yMaxLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.yMaxLabel.setObjectName("yMaxLabel")
        self.gridLayout_6.addWidget(self.yMaxLabel, 0, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.yMinValue = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.yMinValue.setMinimum(-10000)
        self.yMinValue.setMaximum(10000)
        self.yMinValue.setObjectName("yMinValue")
        self.gridLayout_6.addWidget(self.yMinValue, 1, 2, 1, 1)
        self.yMinLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.yMinLabel.setObjectName("yMinLabel")
        self.gridLayout_6.addWidget(self.yMinLabel, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.xMinValue = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.xMinValue.setMinimum(-10000)
        self.xMinValue.setMaximum(10000)
        self.xMinValue.setObjectName("xMinValue")
        self.gridLayout_6.addWidget(self.xMinValue, 1, 0, 1, 1)
        self.yMaxValue = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.yMaxValue.setMinimum(-10000)
        self.yMaxValue.setMaximum(10000)
        self.yMaxValue.setObjectName("yMaxValue")
        self.gridLayout_6.addWidget(self.yMaxValue, 1, 3, 1, 1)
        self.xMinLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.xMinLabel.setObjectName("xMinLabel")
        self.gridLayout_6.addWidget(self.xMinLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.highlightEvent = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.highlightEvent.setObjectName("highlightEvent")
        self.highlightEvent.addItem("")
        self.highlightEvent.addItem("")
        self.highlightEvent.addItem("")
        self.gridLayout_6.addWidget(self.highlightEvent, 1, 4, 1, 1)
        self.highlight = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.highlight.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.highlight.setObjectName("highlight")
        self.gridLayout_6.addWidget(self.highlight, 0, 4, 1, 1)
        self.addInfoL = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.addInfoL.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.addInfoL.setObjectName("addInfoL")
        self.gridLayout_6.addWidget(self.addInfoL, 0, 5, 1, 1)
        self.addInfo = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.addInfo.setObjectName("addInfo")
        self.gridLayout_6.addWidget(self.addInfo, 1, 5, 1, 1)
        self.resetVariables = QtWidgets.QPushButton(self.windowTab)
        self.resetVariables.setGeometry(QtCore.QRect(640, 10, 91, 23))
        self.resetVariables.setObjectName("resetVariables")
        self.heatmapTab.addTab(self.windowTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(9, 19, 131, 51))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plotStyleL = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.plotStyleL.setObjectName("plotStyleL")
        self.gridLayout_7.addWidget(self.plotStyleL, 0, 0, 1, 1)
        self.plotStyle = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.plotStyle.setObjectName("plotStyle")
        self.plotStyle.addItem("")
        self.plotStyle.addItem("")
        self.gridLayout_7.addWidget(self.plotStyle, 1, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 160, 541, 41))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.xCoords = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.xCoords.setObjectName("xCoords")
        self.gridLayout_8.addWidget(self.xCoords, 2, 0, 1, 1)
        self.xCoordsL = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.xCoordsL.setAlignment(QtCore.Qt.AlignCenter)
        self.xCoordsL.setObjectName("xCoordsL")
        self.gridLayout_8.addWidget(self.xCoordsL, 1, 0, 1, 1)
        self.yCoordsL = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.yCoordsL.setAlignment(QtCore.Qt.AlignCenter)
        self.yCoordsL.setObjectName("yCoordsL")
        self.gridLayout_8.addWidget(self.yCoordsL, 1, 1, 1, 1)
        self.yCoords = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.yCoords.setObjectName("yCoords")
        self.gridLayout_8.addWidget(self.yCoords, 2, 1, 1, 1)
        self.time = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.time.setObjectName("time")
        self.gridLayout_8.addWidget(self.time, 2, 3, 1, 1)
        self.speedCoordsL = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.speedCoordsL.setAlignment(QtCore.Qt.AlignCenter)
        self.speedCoordsL.setObjectName("speedCoordsL")
        self.gridLayout_8.addWidget(self.speedCoordsL, 1, 2, 1, 1)
        self.speed = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.speed.setObjectName("speed")
        self.gridLayout_8.addWidget(self.speed, 2, 2, 1, 1)
        self.timeL = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.timeL.setAlignment(QtCore.Qt.AlignCenter)
        self.timeL.setObjectName("timeL")
        self.gridLayout_8.addWidget(self.timeL, 1, 3, 1, 1)
        self.dataInfoLabel = QtWidgets.QLabel(self.tab)
        self.dataInfoLabel.setGeometry(QtCore.QRect(220, 140, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataInfoLabel.setFont(font)
        self.dataInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataInfoLabel.setObjectName("dataInfoLabel")
        self.heatmapTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 721, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.kernelThreshold = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.kernelThreshold.setMinimum(-1.0)
        self.kernelThreshold.setMaximum(1.0)
        self.kernelThreshold.setSingleStep(0.01)
        self.kernelThreshold.setObjectName("kernelThreshold")
        self.gridLayout_4.addWidget(self.kernelThreshold, 1, 5, 1, 1)
        self.kernelScale = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.kernelScale.setMinimum(1)
        self.kernelScale.setMaximum(100)
        self.kernelScale.setObjectName("kernelScale")
        self.gridLayout_4.addWidget(self.kernelScale, 1, 2, 1, 1)
        self.kernelLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.kernelLabel.setObjectName("kernelLabel")
        self.gridLayout_4.addWidget(self.kernelLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelCMLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.kernelCMLabel.setObjectName("kernelCMLabel")
        self.gridLayout_4.addWidget(self.kernelCMLabel, 0, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernel = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.kernel.setObjectName("kernel")
        self.gridLayout_4.addWidget(self.kernel, 1, 0, 1, 1)
        self.kernelCM = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.kernelCM.setObjectName("kernelCM")
        self.gridLayout_4.addWidget(self.kernelCM, 1, 3, 1, 1)
        self.kernelParameter = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.kernelParameter.setMaximum(10000.0)
        self.kernelParameter.setSingleStep(0.01)
        self.kernelParameter.setObjectName("kernelParameter")
        self.gridLayout_4.addWidget(self.kernelParameter, 1, 1, 1, 1)
        self.kernelScaleLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.kernelScaleLabel.setObjectName("kernelScaleLabel")
        self.gridLayout_4.addWidget(self.kernelScaleLabel, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelCMInverse = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.kernelCMInverse.setObjectName("kernelCMInverse")
        self.gridLayout_4.addWidget(self.kernelCMInverse, 1, 4, 1, 1)
        self.kernelParameterLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.kernelParameterLabel.setObjectName("kernelParameterLabel")
        self.gridLayout_4.addWidget(self.kernelParameterLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelAlpha = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.kernelAlpha.setMaximum(1.0)
        self.kernelAlpha.setSingleStep(0.01)
        self.kernelAlpha.setObjectName("kernelAlpha")
        self.gridLayout_4.addWidget(self.kernelAlpha, 1, 6, 1, 1)
        self.kernelCMInverseLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.kernelCMInverseLabel.setObjectName("kernelCMInverseLabel")
        self.gridLayout_4.addWidget(self.kernelCMInverseLabel, 0, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelThresholdLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.kernelThresholdLabel.setObjectName("kernelThresholdLabel")
        self.gridLayout_4.addWidget(self.kernelThresholdLabel, 0, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelAlphaLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.kernelAlphaLabel.setObjectName("kernelAlphaLabel")
        self.gridLayout_4.addWidget(self.kernelAlphaLabel, 0, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.heatmapTab.addTab(self.tab_2, "")
        self.AnimationTab = QtWidgets.QWidget()
        self.AnimationTab.setObjectName("AnimationTab")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.AnimationTab)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 40, 591, 111))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.AnimationLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.AnimationLayout.setContentsMargins(0, 0, 0, 0)
        self.AnimationLayout.setObjectName("AnimationLayout")
        self.useAperture = QtWidgets.QComboBox(self.gridLayoutWidget_9)
        self.useAperture.setObjectName("useAperture")
        self.useAperture.addItem("")
        self.useAperture.addItem("")
        self.AnimationLayout.addWidget(self.useAperture, 3, 0, 1, 1)
        self.apertureRL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.apertureRL.setObjectName("apertureRL")
        self.AnimationLayout.addWidget(self.apertureRL, 2, 1, 1, 1)
        self.edgeOpacL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.edgeOpacL.setObjectName("edgeOpacL")
        self.AnimationLayout.addWidget(self.edgeOpacL, 2, 4, 1, 1)
        self.apertureOpacL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.apertureOpacL.setObjectName("apertureOpacL")
        self.AnimationLayout.addWidget(self.apertureOpacL, 2, 2, 1, 1)
        self.edgeRL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.edgeRL.setObjectName("edgeRL")
        self.AnimationLayout.addWidget(self.edgeRL, 2, 3, 1, 1)
        self.showTraceL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.showTraceL.setObjectName("showTraceL")
        self.AnimationLayout.addWidget(self.showTraceL, 4, 0, 1, 1)
        self.redDotSizeL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.redDotSizeL.setObjectName("redDotSizeL")
        self.AnimationLayout.addWidget(self.redDotSizeL, 4, 2, 1, 1)
        self.blackDotSize = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.blackDotSize.setMinimum(1)
        self.blackDotSize.setMaximum(1000000)
        self.blackDotSize.setProperty("value", 50)
        self.blackDotSize.setObjectName("blackDotSize")
        self.AnimationLayout.addWidget(self.blackDotSize, 5, 1, 1, 1)
        self.showTrace = QtWidgets.QComboBox(self.gridLayoutWidget_9)
        self.showTrace.setObjectName("showTrace")
        self.showTrace.addItem("")
        self.showTrace.addItem("")
        self.AnimationLayout.addWidget(self.showTrace, 5, 0, 1, 1)
        self.saveAnimButton = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.saveAnimButton.setObjectName("saveAnimButton")
        self.AnimationLayout.addWidget(self.saveAnimButton, 5, 4, 1, 1)
        self.frameStepSizeL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.frameStepSizeL.setObjectName("frameStepSizeL")
        self.AnimationLayout.addWidget(self.frameStepSizeL, 4, 3, 1, 1)
        self.blackDotSizeL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.blackDotSizeL.setObjectName("blackDotSizeL")
        self.AnimationLayout.addWidget(self.blackDotSizeL, 4, 1, 1, 1)
        self.redDotSize = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.redDotSize.setMinimum(1)
        self.redDotSize.setMaximum(1000000)
        self.redDotSize.setProperty("value", 20)
        self.redDotSize.setObjectName("redDotSize")
        self.AnimationLayout.addWidget(self.redDotSize, 5, 2, 1, 1)
        self.frameStepSize = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.frameStepSize.setMinimum(1)
        self.frameStepSize.setMaximum(1000)
        self.frameStepSize.setProperty("value", 5)
        self.frameStepSize.setObjectName("frameStepSize")
        self.AnimationLayout.addWidget(self.frameStepSize, 5, 3, 1, 1)
        self.useApertureL = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.useApertureL.setObjectName("useApertureL")
        self.AnimationLayout.addWidget(self.useApertureL, 2, 0, 1, 1)
        self.apertureR = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.apertureR.setMinimum(1)
        self.apertureR.setMaximum(1000)
        self.apertureR.setProperty("value", 75)
        self.apertureR.setObjectName("apertureR")
        self.AnimationLayout.addWidget(self.apertureR, 3, 1, 1, 1)
        self.apertureOpac = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        self.apertureOpac.setMaximum(1.0)
        self.apertureOpac.setSingleStep(0.01)
        self.apertureOpac.setProperty("value", 1.0)
        self.apertureOpac.setObjectName("apertureOpac")
        self.AnimationLayout.addWidget(self.apertureOpac, 3, 2, 1, 1)
        self.edgeOpac = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        self.edgeOpac.setMaximum(1.0)
        self.edgeOpac.setSingleStep(0.01)
        self.edgeOpac.setProperty("value", 0.25)
        self.edgeOpac.setObjectName("edgeOpac")
        self.AnimationLayout.addWidget(self.edgeOpac, 3, 4, 1, 1)
        self.edgeR = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.edgeR.setMinimum(1)
        self.edgeR.setMaximum(1000)
        self.edgeR.setProperty("value", 10)
        self.edgeR.setObjectName("edgeR")
        self.AnimationLayout.addWidget(self.edgeR, 3, 3, 1, 1)
        self.heatmapTab.addTab(self.AnimationTab, "")
        self.settingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.settingsLabel.setGeometry(QtCore.QRect(20, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setAutoFillBackground(False)
        self.settingsLabel.setObjectName("settingsLabel")
        self.settingsLine = QtWidgets.QFrame(self.centralwidget)
        self.settingsLine.setGeometry(QtCore.QRect(10, 190, 771, 20))
        self.settingsLine.setAutoFillBackground(False)
        self.settingsLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.settingsLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.settingsLine.setObjectName("settingsLine")
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.heatmapTab.raise_()
        self.settingsLine.raise_()
        self.settingsLabel.raise_()
        Eyelinkplotter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Eyelinkplotter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Eyelinkplotter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Eyelinkplotter)
        self.statusbar.setObjectName("statusbar")
        Eyelinkplotter.setStatusBar(self.statusbar)
        self.actionSelect_file = QtWidgets.QAction(Eyelinkplotter)
        self.actionSelect_file.setObjectName("actionSelect_file")
        self.menuFile.addAction(self.actionSelect_file)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Eyelinkplotter)
        self.heatmapTab.setCurrentIndex(0)
        self.unLockSettings.toggled['bool'].connect(self.heatmapTab.setVisible)
        self.unLockSettings.toggled['bool'].connect(self.heatmapTab.setEnabled)
        self.unLockSettings.toggled['bool'].connect(self.settingsLabel.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Eyelinkplotter)
        Eyelinkplotter.setTabOrder(self.selectFile, self.selectedFile)
        Eyelinkplotter.setTabOrder(self.selectedFile, self.unLockSettings)

    def retranslateUi(self, Eyelinkplotter):
        _translate = QtCore.QCoreApplication.translate
        Eyelinkplotter.setWindowTitle(_translate("Eyelinkplotter", "MainWindow"))
        self.backButton.setText(_translate("Eyelinkplotter", "Back"))
        self.nextButton.setText(_translate("Eyelinkplotter", "Next"))
        self.updateButton.setText(_translate("Eyelinkplotter", "Update"))
        self.jumpToTrial.setText(_translate("Eyelinkplotter", "Plot trial number"))
        self.trialsToPlot.setItemText(0, _translate("Eyelinkplotter", "All"))
        self.trialsToPlot.setItemText(1, _translate("Eyelinkplotter", "Included"))
        self.trialsToPlot.setItemText(2, _translate("Eyelinkplotter", "Excluded"))
        self.toggleIncluded.setText(_translate("Eyelinkplotter", "Include/Exclude"))
        self.animateButton.setText(_translate("Eyelinkplotter", "Animate"))
        self.selectFile.setText(_translate("Eyelinkplotter", "Select file"))
        self.unLockSettings.setText(_translate("Eyelinkplotter", "Unlock settings"))
        self.saveFile.setText(_translate("Eyelinkplotter", "Save file"))
        self.plotTypeLabel.setText(_translate("Eyelinkplotter", "Plot type"))
        self.aspectRatioLabel.setText(_translate("Eyelinkplotter", "Aspect ratio"))
        self.plotBackground.setItemText(0, _translate("Eyelinkplotter", "False"))
        self.plotBackground.setItemText(1, _translate("Eyelinkplotter", "True"))
        self.backgroundMainLabel.setText(_translate("Eyelinkplotter", "Plot image behind gaze"))
        self.selectImageFolder.setText(_translate("Eyelinkplotter", "Select folder with background images"))
        self.xMaxLabel.setText(_translate("Eyelinkplotter", "xMax"))
        self.yMaxLabel.setText(_translate("Eyelinkplotter", "yMax"))
        self.yMinLabel.setText(_translate("Eyelinkplotter", "yMin"))
        self.xMinLabel.setText(_translate("Eyelinkplotter", "xMin"))
        self.highlightEvent.setItemText(0, _translate("Eyelinkplotter", "None"))
        self.highlightEvent.setItemText(1, _translate("Eyelinkplotter", "Fixation"))
        self.highlightEvent.setItemText(2, _translate("Eyelinkplotter", "Saccade"))
        self.highlight.setText(_translate("Eyelinkplotter", "Highlight"))
        self.addInfoL.setText(_translate("Eyelinkplotter", "Additional info"))
        self.resetVariables.setText(_translate("Eyelinkplotter", "Reset settings"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.windowTab), _translate("Eyelinkplotter", "General"))
        self.plotStyleL.setText(_translate("Eyelinkplotter", "Plot Style"))
        self.plotStyle.setItemText(0, _translate("Eyelinkplotter", "Scatter"))
        self.plotStyle.setItemText(1, _translate("Eyelinkplotter", "Line"))
        self.xCoordsL.setText(_translate("Eyelinkplotter", "X"))
        self.yCoordsL.setText(_translate("Eyelinkplotter", "Y"))
        self.speedCoordsL.setText(_translate("Eyelinkplotter", "Speed"))
        self.timeL.setText(_translate("Eyelinkplotter", "Time"))
        self.dataInfoLabel.setText(_translate("Eyelinkplotter", "Data to plot"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.tab), _translate("Eyelinkplotter", "Gazemap"))
        self.kernelLabel.setText(_translate("Eyelinkplotter", "Kernel"))
        self.kernelCMLabel.setText(_translate("Eyelinkplotter", "Kernel colormap"))
        self.kernelScaleLabel.setText(_translate("Eyelinkplotter", "Kernel scaling"))
        self.kernelParameterLabel.setText(_translate("Eyelinkplotter", "Kernel (parameter)"))
        self.kernelCMInverseLabel.setText(_translate("Eyelinkplotter", "Inverse color"))
        self.kernelThresholdLabel.setText(_translate("Eyelinkplotter", "Kernel threshold"))
        self.kernelAlphaLabel.setText(_translate("Eyelinkplotter", "Kernel alpha"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.tab_2), _translate("Eyelinkplotter", "Heatmap"))
        self.useAperture.setItemText(0, _translate("Eyelinkplotter", "False"))
        self.useAperture.setItemText(1, _translate("Eyelinkplotter", "True"))
        self.apertureRL.setText(_translate("Eyelinkplotter", "Aperture (radius)"))
        self.edgeOpacL.setText(_translate("Eyelinkplotter", "Edge opacity"))
        self.apertureOpacL.setText(_translate("Eyelinkplotter", "Aperture opacity"))
        self.edgeRL.setText(_translate("Eyelinkplotter", "edge (radius)"))
        self.showTraceL.setText(_translate("Eyelinkplotter", "Show gaze trace"))
        self.redDotSizeL.setText(_translate("Eyelinkplotter", "Red dot size (area)"))
        self.showTrace.setCurrentText(_translate("Eyelinkplotter", "False"))
        self.showTrace.setItemText(0, _translate("Eyelinkplotter", "False"))
        self.showTrace.setItemText(1, _translate("Eyelinkplotter", "True"))
        self.saveAnimButton.setText(_translate("Eyelinkplotter", "Save animation"))
        self.frameStepSizeL.setText(_translate("Eyelinkplotter", "Step size (speed)"))
        self.blackDotSizeL.setText(_translate("Eyelinkplotter", "Black dot size (area)"))
        self.useApertureL.setText(_translate("Eyelinkplotter", "Use aperture (slow)"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.AnimationTab), _translate("Eyelinkplotter", "Animation"))
        self.settingsLabel.setText(_translate("Eyelinkplotter", "Settings"))
        self.menuFile.setTitle(_translate("Eyelinkplotter", "File"))
        self.actionSelect_file.setText(_translate("Eyelinkplotter", "Select file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Eyelinkplotter = QtWidgets.QMainWindow()
    ui = Ui_Eyelinkplotter()
    ui.setupUi(Eyelinkplotter)
    Eyelinkplotter.show()
    sys.exit(app.exec_())

