# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotterGUICode.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Eyelinkplotter(object):
    def setupUi(self, Eyelinkplotter):
        Eyelinkplotter.setObjectName("Eyelinkplotter")
        Eyelinkplotter.setEnabled(True)
        Eyelinkplotter.resize(1055, 779)
        self.centralwidget = QtWidgets.QWidget(Eyelinkplotter)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(500, 400))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.heatmapTab = QtWidgets.QTabWidget(self.frame_2)
        self.heatmapTab.setEnabled(True)
        self.heatmapTab.setMaximumSize(QtCore.QSize(500, 400))
        self.heatmapTab.setBaseSize(QtCore.QSize(250, 400))
        self.heatmapTab.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.heatmapTab.setDocumentMode(False)
        self.heatmapTab.setTabsClosable(False)
        self.heatmapTab.setMovable(False)
        self.heatmapTab.setTabBarAutoHide(False)
        self.heatmapTab.setObjectName("heatmapTab")
        self.windowTab = QtWidgets.QWidget()
        self.windowTab.setObjectName("windowTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.windowTab)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plotType = QtWidgets.QComboBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotType.sizePolicy().hasHeightForWidth())
        self.plotType.setSizePolicy(sizePolicy)
        self.plotType.setObjectName("plotType")
        self.gridLayout_3.addWidget(self.plotType, 1, 0, 1, 1)
        self.aspectRatio = QtWidgets.QComboBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aspectRatio.sizePolicy().hasHeightForWidth())
        self.aspectRatio.setSizePolicy(sizePolicy)
        self.aspectRatio.setObjectName("aspectRatio")
        self.gridLayout_3.addWidget(self.aspectRatio, 1, 1, 1, 1)
        self.plotTypeLabel = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotTypeLabel.sizePolicy().hasHeightForWidth())
        self.plotTypeLabel.setSizePolicy(sizePolicy)
        self.plotTypeLabel.setObjectName("plotTypeLabel")
        self.gridLayout_3.addWidget(self.plotTypeLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.aspectRatioLabel = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aspectRatioLabel.sizePolicy().hasHeightForWidth())
        self.aspectRatioLabel.setSizePolicy(sizePolicy)
        self.aspectRatioLabel.setObjectName("aspectRatioLabel")
        self.gridLayout_3.addWidget(self.aspectRatioLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 0, 2, 1)
        self.resetVariables = QtWidgets.QPushButton(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetVariables.sizePolicy().hasHeightForWidth())
        self.resetVariables.setSizePolicy(sizePolicy)
        self.resetVariables.setObjectName("resetVariables")
        self.gridLayout_10.addWidget(self.resetVariables, 0, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.xMaxLabel = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMaxLabel.sizePolicy().hasHeightForWidth())
        self.xMaxLabel.setSizePolicy(sizePolicy)
        self.xMaxLabel.setObjectName("xMaxLabel")
        self.gridLayout_6.addWidget(self.xMaxLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.yMaxLabel = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMaxLabel.sizePolicy().hasHeightForWidth())
        self.yMaxLabel.setSizePolicy(sizePolicy)
        self.yMaxLabel.setObjectName("yMaxLabel")
        self.gridLayout_6.addWidget(self.yMaxLabel, 0, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.xMaxValue = QtWidgets.QSpinBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMaxValue.sizePolicy().hasHeightForWidth())
        self.xMaxValue.setSizePolicy(sizePolicy)
        self.xMaxValue.setMinimum(-10000)
        self.xMaxValue.setMaximum(10000)
        self.xMaxValue.setObjectName("xMaxValue")
        self.gridLayout_6.addWidget(self.xMaxValue, 1, 1, 1, 1)
        self.yMinValue = QtWidgets.QSpinBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMinValue.sizePolicy().hasHeightForWidth())
        self.yMinValue.setSizePolicy(sizePolicy)
        self.yMinValue.setMinimum(-10000)
        self.yMinValue.setMaximum(10000)
        self.yMinValue.setObjectName("yMinValue")
        self.gridLayout_6.addWidget(self.yMinValue, 1, 2, 1, 1)
        self.yMinLabel = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMinLabel.sizePolicy().hasHeightForWidth())
        self.yMinLabel.setSizePolicy(sizePolicy)
        self.yMinLabel.setObjectName("yMinLabel")
        self.gridLayout_6.addWidget(self.yMinLabel, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.xMinValue = QtWidgets.QSpinBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMinValue.sizePolicy().hasHeightForWidth())
        self.xMinValue.setSizePolicy(sizePolicy)
        self.xMinValue.setMinimum(-10000)
        self.xMinValue.setMaximum(10000)
        self.xMinValue.setObjectName("xMinValue")
        self.gridLayout_6.addWidget(self.xMinValue, 1, 0, 1, 1)
        self.yMaxValue = QtWidgets.QSpinBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yMaxValue.sizePolicy().hasHeightForWidth())
        self.yMaxValue.setSizePolicy(sizePolicy)
        self.yMaxValue.setMinimum(-10000)
        self.yMaxValue.setMaximum(10000)
        self.yMaxValue.setObjectName("yMaxValue")
        self.gridLayout_6.addWidget(self.yMaxValue, 1, 3, 1, 1)
        self.xMinLabel = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xMinLabel.sizePolicy().hasHeightForWidth())
        self.xMinLabel.setSizePolicy(sizePolicy)
        self.xMinLabel.setObjectName("xMinLabel")
        self.gridLayout_6.addWidget(self.xMinLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.highlight = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highlight.sizePolicy().hasHeightForWidth())
        self.highlight.setSizePolicy(sizePolicy)
        self.highlight.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.highlight.setObjectName("highlight")
        self.gridLayout_6.addWidget(self.highlight, 0, 4, 1, 1)
        self.highlightEvent = QtWidgets.QComboBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highlightEvent.sizePolicy().hasHeightForWidth())
        self.highlightEvent.setSizePolicy(sizePolicy)
        self.highlightEvent.setObjectName("highlightEvent")
        self.highlightEvent.addItem("")
        self.highlightEvent.addItem("")
        self.highlightEvent.addItem("")
        self.gridLayout_6.addWidget(self.highlightEvent, 1, 4, 1, 1)
        self.addInfo = QtWidgets.QComboBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addInfo.sizePolicy().hasHeightForWidth())
        self.addInfo.setSizePolicy(sizePolicy)
        self.addInfo.setObjectName("addInfo")
        self.gridLayout_6.addWidget(self.addInfo, 1, 5, 1, 1)
        self.addInfoL = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addInfoL.sizePolicy().hasHeightForWidth())
        self.addInfoL.setSizePolicy(sizePolicy)
        self.addInfoL.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.addInfoL.setObjectName("addInfoL")
        self.gridLayout_6.addWidget(self.addInfoL, 0, 5, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 2, 0, 1, 3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plotBackground = QtWidgets.QComboBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotBackground.sizePolicy().hasHeightForWidth())
        self.plotBackground.setSizePolicy(sizePolicy)
        self.plotBackground.setObjectName("plotBackground")
        self.plotBackground.addItem("")
        self.plotBackground.addItem("")
        self.gridLayout_5.addWidget(self.plotBackground, 1, 0, 1, 1)
        self.backgroundMainLabel = QtWidgets.QLabel(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroundMainLabel.sizePolicy().hasHeightForWidth())
        self.backgroundMainLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.backgroundMainLabel.setFont(font)
        self.backgroundMainLabel.setObjectName("backgroundMainLabel")
        self.gridLayout_5.addWidget(self.backgroundMainLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.bgImageVariable = QtWidgets.QComboBox(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgImageVariable.sizePolicy().hasHeightForWidth())
        self.bgImageVariable.setSizePolicy(sizePolicy)
        self.bgImageVariable.setObjectName("bgImageVariable")
        self.gridLayout_5.addWidget(self.bgImageVariable, 1, 2, 1, 1)
        self.selectImageFolder = QtWidgets.QPushButton(self.windowTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectImageFolder.sizePolicy().hasHeightForWidth())
        self.selectImageFolder.setSizePolicy(sizePolicy)
        self.selectImageFolder.setObjectName("selectImageFolder")
        self.gridLayout_5.addWidget(self.selectImageFolder, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 3, 0, 1, 3)
        self.heatmapTab.addTab(self.windowTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.xCoords = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xCoords.sizePolicy().hasHeightForWidth())
        self.xCoords.setSizePolicy(sizePolicy)
        self.xCoords.setObjectName("xCoords")
        self.gridLayout_8.addWidget(self.xCoords, 3, 0, 1, 1)
        self.xCoordsL = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xCoordsL.sizePolicy().hasHeightForWidth())
        self.xCoordsL.setSizePolicy(sizePolicy)
        self.xCoordsL.setAlignment(QtCore.Qt.AlignCenter)
        self.xCoordsL.setObjectName("xCoordsL")
        self.gridLayout_8.addWidget(self.xCoordsL, 2, 0, 1, 1)
        self.yCoordsL = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yCoordsL.sizePolicy().hasHeightForWidth())
        self.yCoordsL.setSizePolicy(sizePolicy)
        self.yCoordsL.setAlignment(QtCore.Qt.AlignCenter)
        self.yCoordsL.setObjectName("yCoordsL")
        self.gridLayout_8.addWidget(self.yCoordsL, 2, 1, 1, 1)
        self.time = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setObjectName("time")
        self.gridLayout_8.addWidget(self.time, 3, 3, 1, 1)
        self.speedCoordsL = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedCoordsL.sizePolicy().hasHeightForWidth())
        self.speedCoordsL.setSizePolicy(sizePolicy)
        self.speedCoordsL.setAlignment(QtCore.Qt.AlignCenter)
        self.speedCoordsL.setObjectName("speedCoordsL")
        self.gridLayout_8.addWidget(self.speedCoordsL, 2, 2, 1, 1)
        self.yCoords = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yCoords.sizePolicy().hasHeightForWidth())
        self.yCoords.setSizePolicy(sizePolicy)
        self.yCoords.setObjectName("yCoords")
        self.gridLayout_8.addWidget(self.yCoords, 3, 1, 1, 1)
        self.speed = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed.sizePolicy().hasHeightForWidth())
        self.speed.setSizePolicy(sizePolicy)
        self.speed.setObjectName("speed")
        self.gridLayout_8.addWidget(self.speed, 3, 2, 1, 1)
        self.plotStyleL = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotStyleL.sizePolicy().hasHeightForWidth())
        self.plotStyleL.setSizePolicy(sizePolicy)
        self.plotStyleL.setObjectName("plotStyleL")
        self.gridLayout_8.addWidget(self.plotStyleL, 0, 0, 1, 1)
        self.timeL = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeL.sizePolicy().hasHeightForWidth())
        self.timeL.setSizePolicy(sizePolicy)
        self.timeL.setAlignment(QtCore.Qt.AlignCenter)
        self.timeL.setObjectName("timeL")
        self.gridLayout_8.addWidget(self.timeL, 2, 3, 1, 1)
        self.plotStyle = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotStyle.sizePolicy().hasHeightForWidth())
        self.plotStyle.setSizePolicy(sizePolicy)
        self.plotStyle.setObjectName("plotStyle")
        self.plotStyle.addItem("")
        self.plotStyle.addItem("")
        self.gridLayout_8.addWidget(self.plotStyle, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.heatmapTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.kernelThreshold = QtWidgets.QDoubleSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelThreshold.sizePolicy().hasHeightForWidth())
        self.kernelThreshold.setSizePolicy(sizePolicy)
        self.kernelThreshold.setMinimum(-1.0)
        self.kernelThreshold.setMaximum(1.0)
        self.kernelThreshold.setSingleStep(0.01)
        self.kernelThreshold.setObjectName("kernelThreshold")
        self.gridLayout_4.addWidget(self.kernelThreshold, 1, 5, 1, 1)
        self.kernelLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelLabel.sizePolicy().hasHeightForWidth())
        self.kernelLabel.setSizePolicy(sizePolicy)
        self.kernelLabel.setObjectName("kernelLabel")
        self.gridLayout_4.addWidget(self.kernelLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelScale = QtWidgets.QSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelScale.sizePolicy().hasHeightForWidth())
        self.kernelScale.setSizePolicy(sizePolicy)
        self.kernelScale.setMinimum(1)
        self.kernelScale.setMaximum(100)
        self.kernelScale.setObjectName("kernelScale")
        self.gridLayout_4.addWidget(self.kernelScale, 1, 2, 1, 1)
        self.kernelCMLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelCMLabel.sizePolicy().hasHeightForWidth())
        self.kernelCMLabel.setSizePolicy(sizePolicy)
        self.kernelCMLabel.setObjectName("kernelCMLabel")
        self.gridLayout_4.addWidget(self.kernelCMLabel, 0, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelParameter = QtWidgets.QDoubleSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelParameter.sizePolicy().hasHeightForWidth())
        self.kernelParameter.setSizePolicy(sizePolicy)
        self.kernelParameter.setMaximum(10000.0)
        self.kernelParameter.setSingleStep(0.01)
        self.kernelParameter.setObjectName("kernelParameter")
        self.gridLayout_4.addWidget(self.kernelParameter, 1, 1, 1, 1)
        self.kernel = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernel.sizePolicy().hasHeightForWidth())
        self.kernel.setSizePolicy(sizePolicy)
        self.kernel.setObjectName("kernel")
        self.gridLayout_4.addWidget(self.kernel, 1, 0, 1, 1)
        self.kernelCM = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelCM.sizePolicy().hasHeightForWidth())
        self.kernelCM.setSizePolicy(sizePolicy)
        self.kernelCM.setObjectName("kernelCM")
        self.gridLayout_4.addWidget(self.kernelCM, 1, 3, 1, 1)
        self.kernelCMInverse = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelCMInverse.sizePolicy().hasHeightForWidth())
        self.kernelCMInverse.setSizePolicy(sizePolicy)
        self.kernelCMInverse.setObjectName("kernelCMInverse")
        self.gridLayout_4.addWidget(self.kernelCMInverse, 1, 4, 1, 1)
        self.kernelScaleLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelScaleLabel.sizePolicy().hasHeightForWidth())
        self.kernelScaleLabel.setSizePolicy(sizePolicy)
        self.kernelScaleLabel.setObjectName("kernelScaleLabel")
        self.gridLayout_4.addWidget(self.kernelScaleLabel, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelParameterLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelParameterLabel.sizePolicy().hasHeightForWidth())
        self.kernelParameterLabel.setSizePolicy(sizePolicy)
        self.kernelParameterLabel.setObjectName("kernelParameterLabel")
        self.gridLayout_4.addWidget(self.kernelParameterLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelThresholdLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelThresholdLabel.sizePolicy().hasHeightForWidth())
        self.kernelThresholdLabel.setSizePolicy(sizePolicy)
        self.kernelThresholdLabel.setObjectName("kernelThresholdLabel")
        self.gridLayout_4.addWidget(self.kernelThresholdLabel, 0, 5, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelAlpha = QtWidgets.QDoubleSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelAlpha.sizePolicy().hasHeightForWidth())
        self.kernelAlpha.setSizePolicy(sizePolicy)
        self.kernelAlpha.setMaximum(1.0)
        self.kernelAlpha.setSingleStep(0.01)
        self.kernelAlpha.setObjectName("kernelAlpha")
        self.gridLayout_4.addWidget(self.kernelAlpha, 1, 6, 1, 1)
        self.kernelCMInverseLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelCMInverseLabel.sizePolicy().hasHeightForWidth())
        self.kernelCMInverseLabel.setSizePolicy(sizePolicy)
        self.kernelCMInverseLabel.setObjectName("kernelCMInverseLabel")
        self.gridLayout_4.addWidget(self.kernelCMInverseLabel, 0, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.kernelAlphaLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernelAlphaLabel.sizePolicy().hasHeightForWidth())
        self.kernelAlphaLabel.setSizePolicy(sizePolicy)
        self.kernelAlphaLabel.setObjectName("kernelAlphaLabel")
        self.gridLayout_4.addWidget(self.kernelAlphaLabel, 0, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 2, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.heatmapTab.addTab(self.tab_2, "")
        self.AnimationTab = QtWidgets.QWidget()
        self.AnimationTab.setObjectName("AnimationTab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.AnimationTab)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.AnimationLayout = QtWidgets.QGridLayout()
        self.AnimationLayout.setObjectName("AnimationLayout")
        self.edgeOpacL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeOpacL.sizePolicy().hasHeightForWidth())
        self.edgeOpacL.setSizePolicy(sizePolicy)
        self.edgeOpacL.setObjectName("edgeOpacL")
        self.AnimationLayout.addWidget(self.edgeOpacL, 1, 4, 1, 1)
        self.useAperture = QtWidgets.QComboBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useAperture.sizePolicy().hasHeightForWidth())
        self.useAperture.setSizePolicy(sizePolicy)
        self.useAperture.setObjectName("useAperture")
        self.useAperture.addItem("")
        self.useAperture.addItem("")
        self.AnimationLayout.addWidget(self.useAperture, 2, 0, 1, 1)
        self.apertureRL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apertureRL.sizePolicy().hasHeightForWidth())
        self.apertureRL.setSizePolicy(sizePolicy)
        self.apertureRL.setObjectName("apertureRL")
        self.AnimationLayout.addWidget(self.apertureRL, 1, 1, 1, 1)
        self.redDotSizeL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redDotSizeL.sizePolicy().hasHeightForWidth())
        self.redDotSizeL.setSizePolicy(sizePolicy)
        self.redDotSizeL.setObjectName("redDotSizeL")
        self.AnimationLayout.addWidget(self.redDotSizeL, 3, 2, 1, 1)
        self.apertureOpacL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apertureOpacL.sizePolicy().hasHeightForWidth())
        self.apertureOpacL.setSizePolicy(sizePolicy)
        self.apertureOpacL.setObjectName("apertureOpacL")
        self.AnimationLayout.addWidget(self.apertureOpacL, 1, 2, 1, 1)
        self.edgeRL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeRL.sizePolicy().hasHeightForWidth())
        self.edgeRL.setSizePolicy(sizePolicy)
        self.edgeRL.setObjectName("edgeRL")
        self.AnimationLayout.addWidget(self.edgeRL, 1, 3, 1, 1)
        self.showTraceL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showTraceL.sizePolicy().hasHeightForWidth())
        self.showTraceL.setSizePolicy(sizePolicy)
        self.showTraceL.setObjectName("showTraceL")
        self.AnimationLayout.addWidget(self.showTraceL, 3, 0, 1, 1)
        self.saveAnimButton = QtWidgets.QPushButton(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAnimButton.sizePolicy().hasHeightForWidth())
        self.saveAnimButton.setSizePolicy(sizePolicy)
        self.saveAnimButton.setObjectName("saveAnimButton")
        self.AnimationLayout.addWidget(self.saveAnimButton, 4, 4, 1, 1)
        self.blackDotSize = QtWidgets.QSpinBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackDotSize.sizePolicy().hasHeightForWidth())
        self.blackDotSize.setSizePolicy(sizePolicy)
        self.blackDotSize.setMinimum(1)
        self.blackDotSize.setMaximum(1000000)
        self.blackDotSize.setProperty("value", 50)
        self.blackDotSize.setObjectName("blackDotSize")
        self.AnimationLayout.addWidget(self.blackDotSize, 4, 1, 1, 1)
        self.showTrace = QtWidgets.QComboBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showTrace.sizePolicy().hasHeightForWidth())
        self.showTrace.setSizePolicy(sizePolicy)
        self.showTrace.setObjectName("showTrace")
        self.showTrace.addItem("")
        self.showTrace.addItem("")
        self.AnimationLayout.addWidget(self.showTrace, 4, 0, 1, 1)
        self.redDotSize = QtWidgets.QSpinBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redDotSize.sizePolicy().hasHeightForWidth())
        self.redDotSize.setSizePolicy(sizePolicy)
        self.redDotSize.setMinimum(1)
        self.redDotSize.setMaximum(1000000)
        self.redDotSize.setProperty("value", 20)
        self.redDotSize.setObjectName("redDotSize")
        self.AnimationLayout.addWidget(self.redDotSize, 4, 2, 1, 1)
        self.frameStepSizeL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameStepSizeL.sizePolicy().hasHeightForWidth())
        self.frameStepSizeL.setSizePolicy(sizePolicy)
        self.frameStepSizeL.setObjectName("frameStepSizeL")
        self.AnimationLayout.addWidget(self.frameStepSizeL, 3, 3, 1, 1)
        self.blackDotSizeL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackDotSizeL.sizePolicy().hasHeightForWidth())
        self.blackDotSizeL.setSizePolicy(sizePolicy)
        self.blackDotSizeL.setObjectName("blackDotSizeL")
        self.AnimationLayout.addWidget(self.blackDotSizeL, 3, 1, 1, 1)
        self.frameStepSize = QtWidgets.QSpinBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameStepSize.sizePolicy().hasHeightForWidth())
        self.frameStepSize.setSizePolicy(sizePolicy)
        self.frameStepSize.setMinimum(1)
        self.frameStepSize.setMaximum(1000)
        self.frameStepSize.setProperty("value", 5)
        self.frameStepSize.setObjectName("frameStepSize")
        self.AnimationLayout.addWidget(self.frameStepSize, 4, 3, 1, 1)
        self.useApertureL = QtWidgets.QLabel(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useApertureL.sizePolicy().hasHeightForWidth())
        self.useApertureL.setSizePolicy(sizePolicy)
        self.useApertureL.setObjectName("useApertureL")
        self.AnimationLayout.addWidget(self.useApertureL, 1, 0, 1, 1)
        self.apertureOpac = QtWidgets.QDoubleSpinBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apertureOpac.sizePolicy().hasHeightForWidth())
        self.apertureOpac.setSizePolicy(sizePolicy)
        self.apertureOpac.setMaximum(1.0)
        self.apertureOpac.setSingleStep(0.01)
        self.apertureOpac.setProperty("value", 1.0)
        self.apertureOpac.setObjectName("apertureOpac")
        self.AnimationLayout.addWidget(self.apertureOpac, 2, 2, 1, 1)
        self.edgeOpac = QtWidgets.QDoubleSpinBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeOpac.sizePolicy().hasHeightForWidth())
        self.edgeOpac.setSizePolicy(sizePolicy)
        self.edgeOpac.setMaximum(1.0)
        self.edgeOpac.setSingleStep(0.01)
        self.edgeOpac.setProperty("value", 0.25)
        self.edgeOpac.setObjectName("edgeOpac")
        self.AnimationLayout.addWidget(self.edgeOpac, 2, 4, 1, 1)
        self.apertureR = QtWidgets.QSpinBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apertureR.sizePolicy().hasHeightForWidth())
        self.apertureR.setSizePolicy(sizePolicy)
        self.apertureR.setMinimum(1)
        self.apertureR.setMaximum(1000)
        self.apertureR.setProperty("value", 75)
        self.apertureR.setObjectName("apertureR")
        self.AnimationLayout.addWidget(self.apertureR, 2, 1, 1, 1)
        self.edgeR = QtWidgets.QSpinBox(self.AnimationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeR.sizePolicy().hasHeightForWidth())
        self.edgeR.setSizePolicy(sizePolicy)
        self.edgeR.setMinimum(1)
        self.edgeR.setMaximum(1000)
        self.edgeR.setProperty("value", 10)
        self.edgeR.setObjectName("edgeR")
        self.AnimationLayout.addWidget(self.edgeR, 2, 3, 1, 1)
        self.gridLayout_13.addLayout(self.AnimationLayout, 1, 0, 1, 1)
        self.heatmapTab.addTab(self.AnimationTab, "")
        self.verticalLayout_2.addWidget(self.heatmapTab)
        self.gridLayout_2.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(500, 1000))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.selectFile = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFile.sizePolicy().hasHeightForWidth())
        self.selectFile.setSizePolicy(sizePolicy)
        self.selectFile.setAutoDefault(False)
        self.selectFile.setDefault(False)
        self.selectFile.setFlat(False)
        self.selectFile.setObjectName("selectFile")
        self.gridLayout.addWidget(self.selectFile, 0, 0, 1, 1)
        self.updateButton = QtWidgets.QPushButton(self.frame)
        self.updateButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateButton.sizePolicy().hasHeightForWidth())
        self.updateButton.setSizePolicy(sizePolicy)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout.addWidget(self.updateButton, 5, 2, 1, 1)
        self.nextButton = QtWidgets.QPushButton(self.frame)
        self.nextButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 5, 4, 1, 1)
        self.trialScroll = QtWidgets.QScrollBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialScroll.sizePolicy().hasHeightForWidth())
        self.trialScroll.setSizePolicy(sizePolicy)
        self.trialScroll.setMaximum(0)
        self.trialScroll.setOrientation(QtCore.Qt.Horizontal)
        self.trialScroll.setObjectName("trialScroll")
        self.gridLayout.addWidget(self.trialScroll, 4, 1, 1, 4)
        self.animateButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animateButton.sizePolicy().hasHeightForWidth())
        self.animateButton.setSizePolicy(sizePolicy)
        self.animateButton.setObjectName("animateButton")
        self.gridLayout.addWidget(self.animateButton, 5, 6, 1, 1)
        self.trialsToPlot = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialsToPlot.sizePolicy().hasHeightForWidth())
        self.trialsToPlot.setSizePolicy(sizePolicy)
        self.trialsToPlot.setObjectName("trialsToPlot")
        self.trialsToPlot.addItem("")
        self.trialsToPlot.addItem("")
        self.trialsToPlot.addItem("")
        self.gridLayout.addWidget(self.trialsToPlot, 5, 0, 1, 1)
        self.saveFile = QtWidgets.QPushButton(self.frame)
        self.saveFile.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveFile.sizePolicy().hasHeightForWidth())
        self.saveFile.setSizePolicy(sizePolicy)
        self.saveFile.setObjectName("saveFile")
        self.gridLayout.addWidget(self.saveFile, 0, 2, 1, 1)
        self.includedOrExcluded = QtWidgets.QLineEdit(self.frame)
        self.includedOrExcluded.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.includedOrExcluded.sizePolicy().hasHeightForWidth())
        self.includedOrExcluded.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.includedOrExcluded.setFont(font)
        self.includedOrExcluded.setObjectName("includedOrExcluded")
        self.gridLayout.addWidget(self.includedOrExcluded, 3, 0, 1, 1)
        self.toggleIncluded = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleIncluded.sizePolicy().hasHeightForWidth())
        self.toggleIncluded.setSizePolicy(sizePolicy)
        self.toggleIncluded.setObjectName("toggleIncluded")
        self.gridLayout.addWidget(self.toggleIncluded, 3, 1, 1, 1)
        self.jumpToTrial = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jumpToTrial.sizePolicy().hasHeightForWidth())
        self.jumpToTrial.setSizePolicy(sizePolicy)
        self.jumpToTrial.setObjectName("jumpToTrial")
        self.gridLayout.addWidget(self.jumpToTrial, 3, 6, 1, 1)
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 5, 1, 1, 1)
        self.currentTrialDisp = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTrialDisp.sizePolicy().hasHeightForWidth())
        self.currentTrialDisp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currentTrialDisp.setFont(font)
        self.currentTrialDisp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.currentTrialDisp.setObjectName("currentTrialDisp")
        self.gridLayout.addWidget(self.currentTrialDisp, 3, 2, 1, 1)
        self.selectedFile = QtWidgets.QLineEdit(self.frame)
        self.selectedFile.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedFile.sizePolicy().hasHeightForWidth())
        self.selectedFile.setSizePolicy(sizePolicy)
        self.selectedFile.setObjectName("selectedFile")
        self.gridLayout.addWidget(self.selectedFile, 0, 1, 1, 1)
        self.jumpToTrialNr = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jumpToTrialNr.sizePolicy().hasHeightForWidth())
        self.jumpToTrialNr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.jumpToTrialNr.setFont(font)
        self.jumpToTrialNr.setMinimum(1)
        self.jumpToTrialNr.setMaximum(1000000)
        self.jumpToTrialNr.setObjectName("jumpToTrialNr")
        self.gridLayout.addWidget(self.jumpToTrialNr, 1, 6, 1, 1)
        self.settingsToggle = QtWidgets.QCheckBox(self.frame)
        self.settingsToggle.setObjectName("settingsToggle")
        self.gridLayout.addWidget(self.settingsToggle, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        self.plotGrid = QtWidgets.QGridLayout()
        self.plotGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotGrid.setVerticalSpacing(12)
        self.plotGrid.setObjectName("plotGrid")
        self.gridLayout_2.addLayout(self.plotGrid, 0, 1, 7, 1)
        Eyelinkplotter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Eyelinkplotter)
        self.statusbar.setObjectName("statusbar")
        Eyelinkplotter.setStatusBar(self.statusbar)
        self.actionSelect_file = QtWidgets.QAction(Eyelinkplotter)
        self.actionSelect_file.setObjectName("actionSelect_file")

        self.retranslateUi(Eyelinkplotter)
        self.heatmapTab.setCurrentIndex(0)
        self.settingsToggle.toggled['bool'].connect(self.heatmapTab.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Eyelinkplotter)

    def retranslateUi(self, Eyelinkplotter):
        _translate = QtCore.QCoreApplication.translate
        Eyelinkplotter.setWindowTitle(_translate("Eyelinkplotter", "Eyetracker data plotter"))
        self.plotTypeLabel.setText(_translate("Eyelinkplotter", "Plot type"))
        self.aspectRatioLabel.setText(_translate("Eyelinkplotter", "Aspect ratio"))
        self.resetVariables.setText(_translate("Eyelinkplotter", "Reset settings"))
        self.xMaxLabel.setText(_translate("Eyelinkplotter", "xMax"))
        self.yMaxLabel.setText(_translate("Eyelinkplotter", "yMax"))
        self.yMinLabel.setText(_translate("Eyelinkplotter", "yMin"))
        self.xMinLabel.setText(_translate("Eyelinkplotter", "xMin"))
        self.highlight.setText(_translate("Eyelinkplotter", "Highlight"))
        self.highlightEvent.setItemText(0, _translate("Eyelinkplotter", "None"))
        self.highlightEvent.setItemText(1, _translate("Eyelinkplotter", "Fixation"))
        self.highlightEvent.setItemText(2, _translate("Eyelinkplotter", "Saccade"))
        self.addInfoL.setText(_translate("Eyelinkplotter", "Additional info"))
        self.plotBackground.setItemText(0, _translate("Eyelinkplotter", "False"))
        self.plotBackground.setItemText(1, _translate("Eyelinkplotter", "True"))
        self.backgroundMainLabel.setText(_translate("Eyelinkplotter", "Plot image behind gaze"))
        self.selectImageFolder.setText(_translate("Eyelinkplotter", "Select folder with background images"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.windowTab), _translate("Eyelinkplotter", "General"))
        self.xCoordsL.setText(_translate("Eyelinkplotter", "X"))
        self.yCoordsL.setText(_translate("Eyelinkplotter", "Y"))
        self.speedCoordsL.setText(_translate("Eyelinkplotter", "Speed"))
        self.plotStyleL.setText(_translate("Eyelinkplotter", "Plot Style"))
        self.timeL.setText(_translate("Eyelinkplotter", "Time"))
        self.plotStyle.setItemText(0, _translate("Eyelinkplotter", "Scatter"))
        self.plotStyle.setItemText(1, _translate("Eyelinkplotter", "Line"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.tab), _translate("Eyelinkplotter", "Gazemap"))
        self.kernelLabel.setText(_translate("Eyelinkplotter", "Kernel"))
        self.kernelCMLabel.setText(_translate("Eyelinkplotter", "Kernel colormap"))
        self.kernelScaleLabel.setText(_translate("Eyelinkplotter", "Kernel scaling"))
        self.kernelParameterLabel.setText(_translate("Eyelinkplotter", "Kernel (parameter)"))
        self.kernelThresholdLabel.setText(_translate("Eyelinkplotter", "Kernel threshold"))
        self.kernelCMInverseLabel.setText(_translate("Eyelinkplotter", "Inverse color"))
        self.kernelAlphaLabel.setText(_translate("Eyelinkplotter", "Kernel alpha"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.tab_2), _translate("Eyelinkplotter", "Heatmap"))
        self.edgeOpacL.setText(_translate("Eyelinkplotter", "Edge opacity"))
        self.useAperture.setItemText(0, _translate("Eyelinkplotter", "False"))
        self.useAperture.setItemText(1, _translate("Eyelinkplotter", "True"))
        self.apertureRL.setText(_translate("Eyelinkplotter", "Aperture (radius)"))
        self.redDotSizeL.setText(_translate("Eyelinkplotter", "Red dot size (area)"))
        self.apertureOpacL.setText(_translate("Eyelinkplotter", "Aperture opacity"))
        self.edgeRL.setText(_translate("Eyelinkplotter", "edge (radius)"))
        self.showTraceL.setText(_translate("Eyelinkplotter", "Show gaze trace"))
        self.saveAnimButton.setText(_translate("Eyelinkplotter", "Save animation"))
        self.showTrace.setCurrentText(_translate("Eyelinkplotter", "False"))
        self.showTrace.setItemText(0, _translate("Eyelinkplotter", "False"))
        self.showTrace.setItemText(1, _translate("Eyelinkplotter", "True"))
        self.frameStepSizeL.setText(_translate("Eyelinkplotter", "Step size (speed)"))
        self.blackDotSizeL.setText(_translate("Eyelinkplotter", "Black dot size (area)"))
        self.useApertureL.setText(_translate("Eyelinkplotter", "Use aperture (slow)"))
        self.heatmapTab.setTabText(self.heatmapTab.indexOf(self.AnimationTab), _translate("Eyelinkplotter", "Animation"))
        self.selectFile.setText(_translate("Eyelinkplotter", "Select file"))
        self.updateButton.setText(_translate("Eyelinkplotter", "Update"))
        self.nextButton.setText(_translate("Eyelinkplotter", "Next"))
        self.animateButton.setText(_translate("Eyelinkplotter", "Animate"))
        self.trialsToPlot.setItemText(0, _translate("Eyelinkplotter", "All"))
        self.trialsToPlot.setItemText(1, _translate("Eyelinkplotter", "Included"))
        self.trialsToPlot.setItemText(2, _translate("Eyelinkplotter", "Excluded"))
        self.saveFile.setText(_translate("Eyelinkplotter", "Save file"))
        self.toggleIncluded.setText(_translate("Eyelinkplotter", "Include/Exclude"))
        self.jumpToTrial.setText(_translate("Eyelinkplotter", "Plot trial number"))
        self.backButton.setText(_translate("Eyelinkplotter", "Back"))
        self.settingsToggle.setText(_translate("Eyelinkplotter", "Settings"))
        self.actionSelect_file.setText(_translate("Eyelinkplotter", "Select file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Eyelinkplotter = QtWidgets.QMainWindow()
    ui = Ui_Eyelinkplotter()
    ui.setupUi(Eyelinkplotter)
    Eyelinkplotter.show()
    sys.exit(app.exec_())

