# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eyeParserBuilder.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(804, 773)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.settingsL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsL.sizePolicy().hasHeightForWidth())
        self.settingsL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.settingsL.setFont(font)
        self.settingsL.setObjectName(_fromUtf8("settingsL"))
        self.verticalLayout.addWidget(self.settingsL)
        self.settingsLine = QtGui.QFrame(self.centralwidget)
        self.settingsLine.setBaseSize(QtCore.QSize(0, 0))
        self.settingsLine.setLineWidth(5)
        self.settingsLine.setFrameShape(QtGui.QFrame.HLine)
        self.settingsLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.settingsLine.setObjectName(_fromUtf8("settingsLine"))
        self.verticalLayout.addWidget(self.settingsLine)
        self.regL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regL.sizePolicy().hasHeightForWidth())
        self.regL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.regL.setFont(font)
        self.regL.setObjectName(_fromUtf8("regL"))
        self.verticalLayout.addWidget(self.regL)
        self.regSampL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regSampL.sizePolicy().hasHeightForWidth())
        self.regSampL.setSizePolicy(sizePolicy)
        self.regSampL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regSampL.setObjectName(_fromUtf8("regSampL"))
        self.verticalLayout.addWidget(self.regSampL)
        self.regSamp = QtGui.QTextEdit(self.centralwidget)
        self.regSamp.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regSamp.sizePolicy().hasHeightForWidth())
        self.regSamp.setSizePolicy(sizePolicy)
        self.regSamp.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regSamp.setObjectName(_fromUtf8("regSamp"))
        self.verticalLayout.addWidget(self.regSamp)
        self.regEfixL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEfixL.sizePolicy().hasHeightForWidth())
        self.regEfixL.setSizePolicy(sizePolicy)
        self.regEfixL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEfixL.setObjectName(_fromUtf8("regEfixL"))
        self.verticalLayout.addWidget(self.regEfixL)
        self.regEfix = QtGui.QTextEdit(self.centralwidget)
        self.regEfix.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEfix.sizePolicy().hasHeightForWidth())
        self.regEfix.setSizePolicy(sizePolicy)
        self.regEfix.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEfix.setObjectName(_fromUtf8("regEfix"))
        self.verticalLayout.addWidget(self.regEfix)
        self.regEsaccL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEsaccL.sizePolicy().hasHeightForWidth())
        self.regEsaccL.setSizePolicy(sizePolicy)
        self.regEsaccL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEsaccL.setObjectName(_fromUtf8("regEsaccL"))
        self.verticalLayout.addWidget(self.regEsaccL)
        self.regEsacc = QtGui.QTextEdit(self.centralwidget)
        self.regEsacc.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEsacc.sizePolicy().hasHeightForWidth())
        self.regEsacc.setSizePolicy(sizePolicy)
        self.regEsacc.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEsacc.setObjectName(_fromUtf8("regEsacc"))
        self.verticalLayout.addWidget(self.regEsacc)
        self.regEblinkL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEblinkL.sizePolicy().hasHeightForWidth())
        self.regEblinkL.setSizePolicy(sizePolicy)
        self.regEblinkL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEblinkL.setObjectName(_fromUtf8("regEblinkL"))
        self.verticalLayout.addWidget(self.regEblinkL)
        self.regEblink = QtGui.QTextEdit(self.centralwidget)
        self.regEblink.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regEblink.sizePolicy().hasHeightForWidth())
        self.regEblink.setSizePolicy(sizePolicy)
        self.regEblink.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regEblink.setObjectName(_fromUtf8("regEblink"))
        self.verticalLayout.addWidget(self.regEblink)
        self.regStartL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStartL.sizePolicy().hasHeightForWidth())
        self.regStartL.setSizePolicy(sizePolicy)
        self.regStartL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStartL.setObjectName(_fromUtf8("regStartL"))
        self.verticalLayout.addWidget(self.regStartL)
        self.regStart = QtGui.QTextEdit(self.centralwidget)
        self.regStart.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStart.sizePolicy().hasHeightForWidth())
        self.regStart.setSizePolicy(sizePolicy)
        self.regStart.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStart.setBaseSize(QtCore.QSize(0, 0))
        self.regStart.setObjectName(_fromUtf8("regStart"))
        self.verticalLayout.addWidget(self.regStart)
        self.regStopL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStopL.sizePolicy().hasHeightForWidth())
        self.regStopL.setSizePolicy(sizePolicy)
        self.regStopL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStopL.setObjectName(_fromUtf8("regStopL"))
        self.verticalLayout.addWidget(self.regStopL)
        self.regStop = QtGui.QTextEdit(self.centralwidget)
        self.regStop.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regStop.sizePolicy().hasHeightForWidth())
        self.regStop.setSizePolicy(sizePolicy)
        self.regStop.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regStop.setObjectName(_fromUtf8("regStop"))
        self.verticalLayout.addWidget(self.regStop)
        self.regVarL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regVarL.sizePolicy().hasHeightForWidth())
        self.regVarL.setSizePolicy(sizePolicy)
        self.regVarL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regVarL.setObjectName(_fromUtf8("regVarL"))
        self.verticalLayout.addWidget(self.regVarL)
        self.regVar = QtGui.QTextEdit(self.centralwidget)
        self.regVar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regVar.sizePolicy().hasHeightForWidth())
        self.regVar.setSizePolicy(sizePolicy)
        self.regVar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regVar.setObjectName(_fromUtf8("regVar"))
        self.verticalLayout.addWidget(self.regVar)
        self.regMsgL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regMsgL.sizePolicy().hasHeightForWidth())
        self.regMsgL.setSizePolicy(sizePolicy)
        self.regMsgL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regMsgL.setObjectName(_fromUtf8("regMsgL"))
        self.verticalLayout.addWidget(self.regMsgL)
        self.regMsg = QtGui.QTextEdit(self.centralwidget)
        self.regMsg.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regMsg.sizePolicy().hasHeightForWidth())
        self.regMsg.setSizePolicy(sizePolicy)
        self.regMsg.setMaximumSize(QtCore.QSize(16777215, 25))
        self.regMsg.setObjectName(_fromUtf8("regMsg"))
        self.verticalLayout.addWidget(self.regMsg)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mergeL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeL.sizePolicy().hasHeightForWidth())
        self.mergeL.setSizePolicy(sizePolicy)
        self.mergeL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mergeL.setObjectName(_fromUtf8("mergeL"))
        self.gridLayout_3.addWidget(self.mergeL, 1, 3, 1, 1)
        self.rawNameL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawNameL.sizePolicy().hasHeightForWidth())
        self.rawNameL.setSizePolicy(sizePolicy)
        self.rawNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rawNameL.setObjectName(_fromUtf8("rawNameL"))
        self.gridLayout_3.addWidget(self.rawNameL, 1, 1, 1, 1)
        self.mergedName = QtGui.QTextEdit(self.centralwidget)
        self.mergedName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergedName.sizePolicy().hasHeightForWidth())
        self.mergedName.setSizePolicy(sizePolicy)
        self.mergedName.setMaximumSize(QtCore.QSize(100, 25))
        self.mergedName.setObjectName(_fromUtf8("mergedName"))
        self.gridLayout_3.addWidget(self.mergedName, 2, 2, 1, 1)
        self.mergebtn = QtGui.QComboBox(self.centralwidget)
        self.mergebtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergebtn.sizePolicy().hasHeightForWidth())
        self.mergebtn.setSizePolicy(sizePolicy)
        self.mergebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.mergebtn.setObjectName(_fromUtf8("mergebtn"))
        self.gridLayout_3.addWidget(self.mergebtn, 2, 3, 1, 1)
        self.duplicLongL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duplicLongL.sizePolicy().hasHeightForWidth())
        self.duplicLongL.setSizePolicy(sizePolicy)
        self.duplicLongL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.duplicLongL.setObjectName(_fromUtf8("duplicLongL"))
        self.gridLayout_3.addWidget(self.duplicLongL, 4, 4, 1, 1)
        self.longL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longL.sizePolicy().hasHeightForWidth())
        self.longL.setSizePolicy(sizePolicy)
        self.longL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.longL.setObjectName(_fromUtf8("longL"))
        self.gridLayout_3.addWidget(self.longL, 4, 3, 1, 1)
        self.parsedNameL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parsedNameL.sizePolicy().hasHeightForWidth())
        self.parsedNameL.setSizePolicy(sizePolicy)
        self.parsedNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.parsedNameL.setObjectName(_fromUtf8("parsedNameL"))
        self.gridLayout_3.addWidget(self.parsedNameL, 1, 0, 1, 1)
        self.parsedName = QtGui.QTextEdit(self.centralwidget)
        self.parsedName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parsedName.sizePolicy().hasHeightForWidth())
        self.parsedName.setSizePolicy(sizePolicy)
        self.parsedName.setMaximumSize(QtCore.QSize(100, 25))
        self.parsedName.setObjectName(_fromUtf8("parsedName"))
        self.gridLayout_3.addWidget(self.parsedName, 2, 0, 1, 1)
        self.variousL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variousL.sizePolicy().hasHeightForWidth())
        self.variousL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.variousL.setFont(font)
        self.variousL.setObjectName(_fromUtf8("variousL"))
        self.gridLayout_3.addWidget(self.variousL, 0, 0, 1, 1)
        self.saveRawL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawL.sizePolicy().hasHeightForWidth())
        self.saveRawL.setSizePolicy(sizePolicy)
        self.saveRawL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.saveRawL.setObjectName(_fromUtf8("saveRawL"))
        self.gridLayout_3.addWidget(self.saveRawL, 1, 4, 1, 1)
        self.pixDegL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixDegL.sizePolicy().hasHeightForWidth())
        self.pixDegL.setSizePolicy(sizePolicy)
        self.pixDegL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pixDegL.setObjectName(_fromUtf8("pixDegL"))
        self.gridLayout_3.addWidget(self.pixDegL, 4, 1, 1, 1)
        self.rawName = QtGui.QTextEdit(self.centralwidget)
        self.rawName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawName.sizePolicy().hasHeightForWidth())
        self.rawName.setSizePolicy(sizePolicy)
        self.rawName.setMaximumSize(QtCore.QSize(100, 25))
        self.rawName.setObjectName(_fromUtf8("rawName"))
        self.gridLayout_3.addWidget(self.rawName, 2, 1, 1, 1)
        self.mergedNameL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergedNameL.sizePolicy().hasHeightForWidth())
        self.mergedNameL.setSizePolicy(sizePolicy)
        self.mergedNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mergedNameL.setObjectName(_fromUtf8("mergedNameL"))
        self.gridLayout_3.addWidget(self.mergedNameL, 1, 2, 1, 1)
        self.closebtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closebtn.sizePolicy().hasHeightForWidth())
        self.closebtn.setSizePolicy(sizePolicy)
        self.closebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.closebtn.setObjectName(_fromUtf8("closebtn"))
        self.gridLayout_3.addWidget(self.closebtn, 8, 2, 1, 1)
        self.pixPerDeg = QtGui.QTextEdit(self.centralwidget)
        self.pixPerDeg.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixPerDeg.sizePolicy().hasHeightForWidth())
        self.pixPerDeg.setSizePolicy(sizePolicy)
        self.pixPerDeg.setMaximumSize(QtCore.QSize(100, 25))
        self.pixPerDeg.setObjectName(_fromUtf8("pixPerDeg"))
        self.gridLayout_3.addWidget(self.pixPerDeg, 7, 1, 1, 1)
        self.nrCores = QtGui.QTextEdit(self.centralwidget)
        self.nrCores.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nrCores.sizePolicy().hasHeightForWidth())
        self.nrCores.setSizePolicy(sizePolicy)
        self.nrCores.setMaximumSize(QtCore.QSize(100, 25))
        self.nrCores.setObjectName(_fromUtf8("nrCores"))
        self.gridLayout_3.addWidget(self.nrCores, 7, 0, 1, 1)
        self.pixPerDegL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixPerDegL.sizePolicy().hasHeightForWidth())
        self.pixPerDegL.setSizePolicy(sizePolicy)
        self.pixPerDegL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pixPerDegL.setObjectName(_fromUtf8("pixPerDegL"))
        self.gridLayout_3.addWidget(self.pixPerDegL, 6, 1, 1, 1)
        self.nrCoresL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nrCoresL.sizePolicy().hasHeightForWidth())
        self.nrCoresL.setSizePolicy(sizePolicy)
        self.nrCoresL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.nrCoresL.setObjectName(_fromUtf8("nrCoresL"))
        self.gridLayout_3.addWidget(self.nrCoresL, 6, 0, 1, 1)
        self.longbtn = QtGui.QComboBox(self.centralwidget)
        self.longbtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longbtn.sizePolicy().hasHeightForWidth())
        self.longbtn.setSizePolicy(sizePolicy)
        self.longbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.longbtn.setObjectName(_fromUtf8("longbtn"))
        self.gridLayout_3.addWidget(self.longbtn, 5, 3, 1, 1)
        self.duplicLongbtn = QtGui.QComboBox(self.centralwidget)
        self.duplicLongbtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duplicLongbtn.sizePolicy().hasHeightForWidth())
        self.duplicLongbtn.setSizePolicy(sizePolicy)
        self.duplicLongbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.duplicLongbtn.setObjectName(_fromUtf8("duplicLongbtn"))
        self.gridLayout_3.addWidget(self.duplicLongbtn, 5, 4, 1, 1)
        self.paralell = QtGui.QComboBox(self.centralwidget)
        self.paralell.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paralell.sizePolicy().hasHeightForWidth())
        self.paralell.setSizePolicy(sizePolicy)
        self.paralell.setMaximumSize(QtCore.QSize(100, 25))
        self.paralell.setObjectName(_fromUtf8("paralell"))
        self.gridLayout_3.addWidget(self.paralell, 5, 0, 1, 1)
        self.pixMode = QtGui.QComboBox(self.centralwidget)
        self.pixMode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixMode.sizePolicy().hasHeightForWidth())
        self.pixMode.setSizePolicy(sizePolicy)
        self.pixMode.setMaximumSize(QtCore.QSize(100, 25))
        self.pixMode.setObjectName(_fromUtf8("pixMode"))
        self.gridLayout_3.addWidget(self.pixMode, 5, 1, 1, 1)
        self.saveRawbtn = QtGui.QComboBox(self.centralwidget)
        self.saveRawbtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawbtn.sizePolicy().hasHeightForWidth())
        self.saveRawbtn.setSizePolicy(sizePolicy)
        self.saveRawbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.saveRawbtn.setObjectName(_fromUtf8("saveRawbtn"))
        self.gridLayout_3.addWidget(self.saveRawbtn, 2, 4, 1, 1)
        self.paralellL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paralellL.sizePolicy().hasHeightForWidth())
        self.paralellL.setSizePolicy(sizePolicy)
        self.paralellL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.paralellL.setObjectName(_fromUtf8("paralellL"))
        self.gridLayout_3.addWidget(self.paralellL, 4, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textbox = QtGui.QTextEdit(self.centralwidget)
        self.textbox.setEnabled(False)
        self.textbox.setObjectName(_fromUtf8("textbox"))
        self.gridLayout_2.addWidget(self.textbox, 1, 0, 1, 1)
        self.filebtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filebtn.sizePolicy().hasHeightForWidth())
        self.filebtn.setSizePolicy(sizePolicy)
        self.filebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.filebtn.setObjectName(_fromUtf8("filebtn"))
        self.gridLayout_2.addWidget(self.filebtn, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 2, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.varKeyL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varKeyL.sizePolicy().hasHeightForWidth())
        self.varKeyL.setSizePolicy(sizePolicy)
        self.varKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.varKeyL.setObjectName(_fromUtf8("varKeyL"))
        self.gridLayout.addWidget(self.varKeyL, 0, 2, 1, 1)
        self.startKey = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startKey.sizePolicy().hasHeightForWidth())
        self.startKey.setSizePolicy(sizePolicy)
        self.startKey.setMaximumSize(QtCore.QSize(100, 25))
        self.startKey.setObjectName(_fromUtf8("startKey"))
        self.gridLayout.addWidget(self.startKey, 1, 0, 1, 1)
        self.Parsebtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Parsebtn.sizePolicy().hasHeightForWidth())
        self.Parsebtn.setSizePolicy(sizePolicy)
        self.Parsebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.Parsebtn.setObjectName(_fromUtf8("Parsebtn"))
        self.gridLayout.addWidget(self.Parsebtn, 1, 3, 1, 1)
        self.varKey = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varKey.sizePolicy().hasHeightForWidth())
        self.varKey.setSizePolicy(sizePolicy)
        self.varKey.setMaximumSize(QtCore.QSize(100, 25))
        self.varKey.setObjectName(_fromUtf8("varKey"))
        self.gridLayout.addWidget(self.varKey, 1, 2, 1, 1)
        self.startKeyL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startKeyL.sizePolicy().hasHeightForWidth())
        self.startKeyL.setSizePolicy(sizePolicy)
        self.startKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.startKeyL.setObjectName(_fromUtf8("startKeyL"))
        self.gridLayout.addWidget(self.startKeyL, 0, 0, 1, 1)
        self.stopKeyL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopKeyL.sizePolicy().hasHeightForWidth())
        self.stopKeyL.setSizePolicy(sizePolicy)
        self.stopKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.stopKeyL.setObjectName(_fromUtf8("stopKeyL"))
        self.gridLayout.addWidget(self.stopKeyL, 0, 1, 1, 1)
        self.stopKey = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopKey.sizePolicy().hasHeightForWidth())
        self.stopKey.setSizePolicy(sizePolicy)
        self.stopKey.setMaximumSize(QtCore.QSize(100, 25))
        self.stopKey.setObjectName(_fromUtf8("stopKey"))
        self.gridLayout.addWidget(self.stopKey, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.statusL = QtGui.QLabel(self.centralwidget)
        self.statusL.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusL.setFont(font)
        self.statusL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusL.setAlignment(QtCore.Qt.AlignCenter)
        self.statusL.setObjectName(_fromUtf8("statusL"))
        self.verticalLayout_2.addWidget(self.statusL)
        self.bussyBar = QtGui.QProgressBar(self.centralwidget)
        self.bussyBar.setMaximum(1)
        self.bussyBar.setProperty("value", -1)
        self.bussyBar.setObjectName(_fromUtf8("bussyBar"))
        self.verticalLayout_2.addWidget(self.bussyBar)
        self.progressBarL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarL.sizePolicy().hasHeightForWidth())
        self.progressBarL.setSizePolicy(sizePolicy)
        self.progressBarL.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBarL.setFont(font)
        self.progressBarL.setScaledContents(False)
        self.progressBarL.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBarL.setObjectName(_fromUtf8("progressBarL"))
        self.verticalLayout_2.addWidget(self.progressBarL)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.cpuBarL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuBarL.sizePolicy().hasHeightForWidth())
        self.cpuBarL.setSizePolicy(sizePolicy)
        self.cpuBarL.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cpuBarL.setFont(font)
        self.cpuBarL.setObjectName(_fromUtf8("cpuBarL"))
        self.verticalLayout_2.addWidget(self.cpuBarL)
        self.cpuBar = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuBar.sizePolicy().hasHeightForWidth())
        self.cpuBar.setSizePolicy(sizePolicy)
        self.cpuBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.cpuBar.setProperty("value", 24)
        self.cpuBar.setObjectName(_fromUtf8("cpuBar"))
        self.verticalLayout_2.addWidget(self.cpuBar)
        self.memBarL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memBarL.sizePolicy().hasHeightForWidth())
        self.memBarL.setSizePolicy(sizePolicy)
        self.memBarL.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.memBarL.setFont(font)
        self.memBarL.setObjectName(_fromUtf8("memBarL"))
        self.verticalLayout_2.addWidget(self.memBarL)
        self.memBar = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memBar.sizePolicy().hasHeightForWidth())
        self.memBar.setSizePolicy(sizePolicy)
        self.memBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.memBar.setProperty("value", 24)
        self.memBar.setObjectName(_fromUtf8("memBar"))
        self.verticalLayout_2.addWidget(self.memBar)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.openFile = QtGui.QAction(MainWindow)
        self.openFile.setObjectName(_fromUtf8("openFile"))
        self.quitParser = QtGui.QAction(MainWindow)
        self.quitParser.setShortcut(_fromUtf8(""))
        self.quitParser.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.quitParser.setObjectName(_fromUtf8("quitParser"))
        self.unlockSettingsM = QtGui.QAction(MainWindow)
        self.unlockSettingsM.setObjectName(_fromUtf8("unlockSettingsM"))
        self.lockSettingsM = QtGui.QAction(MainWindow)
        self.lockSettingsM.setEnabled(False)
        self.lockSettingsM.setObjectName(_fromUtf8("lockSettingsM"))
        self.defSett = QtGui.QAction(MainWindow)
        self.defSett.setObjectName(_fromUtf8("defSett"))
        self.openDoc = QtGui.QAction(MainWindow)
        self.openDoc.setObjectName(_fromUtf8("openDoc"))
        self.menuFile.addAction(self.openFile)
        self.menuFile.addAction(self.quitParser)
        self.menuSettings.addAction(self.unlockSettingsM)
        self.menuSettings.addAction(self.lockSettingsM)
        self.menuSettings.addAction(self.defSett)
        self.menuSettings.addAction(self.openDoc)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Eyelink 100 parser", None))
        self.settingsL.setText(_translate("MainWindow", "Settings", None))
        self.regL.setText(_translate("MainWindow", "Regular expressions for data extraction", None))
        self.regSampL.setText(_translate("MainWindow", "Samples", None))
        self.regEfixL.setText(_translate("MainWindow", "End fixation", None))
        self.regEsaccL.setText(_translate("MainWindow", "End Saccade", None))
        self.regEblinkL.setText(_translate("MainWindow", "End blink", None))
        self.regStartL.setText(_translate("MainWindow", "Start trial", None))
        self.regStopL.setText(_translate("MainWindow", "Stop trial", None))
        self.regVarL.setText(_translate("MainWindow", "Variables", None))
        self.regMsgL.setText(_translate("MainWindow", "Other messages", None))
        self.mergeL.setText(_translate("MainWindow", "Merge files", None))
        self.rawNameL.setText(_translate("MainWindow", "Raw name", None))
        self.duplicLongL.setText(_translate("MainWindow", "Duplicate values", None))
        self.longL.setText(_translate("MainWindow", "Save longformat", None))
        self.parsedNameL.setText(_translate("MainWindow", "Parsed name", None))
        self.variousL.setText(_translate("MainWindow", "Various settings", None))
        self.saveRawL.setText(_translate("MainWindow", "Save raw file", None))
        self.pixDegL.setText(_translate("MainWindow", "Pixels per degree", None))
        self.mergedNameL.setText(_translate("MainWindow", "Merged name", None))
        self.closebtn.setText(_translate("MainWindow", "Close", None))
        self.pixPerDegL.setText(_translate("MainWindow", "Px per deg (manual)", None))
        self.nrCoresL.setText(_translate("MainWindow", "CPU cores", None))
        self.paralellL.setText(_translate("MainWindow", "Parallel processing", None))
        self.filebtn.setText(_translate("MainWindow", "Select file(s)", None))
        self.varKeyL.setText(_translate("MainWindow", "Variable prefix", None))
        self.Parsebtn.setText(_translate("MainWindow", "Parse", None))
        self.startKeyL.setText(_translate("MainWindow", "Start trial key", None))
        self.stopKeyL.setText(_translate("MainWindow", "Stop trial key", None))
        self.statusL.setText(_translate("MainWindow", "Parallel processing!", None))
        self.progressBarL.setText(_translate("MainWindow", "% of files Finished", None))
        self.cpuBarL.setText(_translate("MainWindow", "CPU usage", None))
        self.memBarL.setText(_translate("MainWindow", "Memory usage", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.openFile.setText(_translate("MainWindow", "Select files(s)", None))
        self.openFile.setStatusTip(_translate("MainWindow", "Select file(s)", None))
        self.quitParser.setText(_translate("MainWindow", "Exit", None))
        self.quitParser.setStatusTip(_translate("MainWindow", "Exit parser", None))
        self.unlockSettingsM.setText(_translate("MainWindow", "Unlock settings", None))
        self.unlockSettingsM.setStatusTip(_translate("MainWindow", "Unlock settings", None))
        self.lockSettingsM.setText(_translate("MainWindow", "Lock settings", None))
        self.lockSettingsM.setStatusTip(_translate("MainWindow", "Lock settings", None))
        self.defSett.setText(_translate("MainWindow", "Load default settings", None))
        self.defSett.setStatusTip(_translate("MainWindow", "Load default setings", None))
        self.openDoc.setText(_translate("MainWindow", "Documentation", None))
        self.openDoc.setStatusTip(_translate("MainWindow", "Open documentation", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

